### ISSUE TITLE
AES encryption

### ISSUE THREAD

**Issue by teidesu** [awslabs/llrt#125]
there currently seems to be no way to do AES en/decryption, which is essential for many applications

`require('crypto')` doesn't include `createCipheriv`/`createDecipheriv`:
![](https://github.com/awslabs/llrt/assets/86301490/46ac9df5-9b30-4cd4-8385-92aad2db291e)

and SubtleCrypto doesn't seem to be implemented either

**Comment by richarddavison** [comment]
`SubtleCrypto` is on the roadmap!
https://w3c.github.io/webcrypto/#dfn-SubtleCrypto

What APIs is a blocker for you?
-  `subtle.importKey`
- `subtle.encrypt`
- `subtle.decrypt`

Will be prioritized.

**Comment by teidesu** [comment]
> are a blocker for you

not really a blocker, i was just poking around for fun c:

**Comment by richarddavison** [comment]
Dup of https://github.com/awslabs/llrt/issues/125

**Comment by jackkleeman** [comment]
@richarddavison this is #125 - it can't be a dupe of itself :p

**Comment by richarddavison** [comment]
> @richarddavison this is #125 - it can't be a dupe of itself :p

Issueception? 😵‍💫  I don't seem to have a copy and paste license... 🤦‍♂️
