### ISSUE TITLE
process.versions is undefined

### ISSUE THREAD

**Issue by p0wl** [awslabs/llrt#126]
I wanted to try LLRT via https://github.com/tmokmss/cdk-lambda-llrt, but the lambda execution fails on initialization, as a library we use ([pg-promise](https://github.com/vitaly-t/pg-promise/blob/master/lib/index.js#L11)) relies on process.versions.node to be set.

In LLRT `process.version` is set, but `process.versions` is not (see [nodejs](https://nodejs.org/docs/latest-v18.x/api/process.html#processversions) docs).

I can see that llrt would not return `process.versions.node` with a valid nodejs version number (since it is not a nodejs version), but LLRT should probably return some kind of object for `process.versions` at least, right?

Thanks for your work!

**Comment by richarddavison** [comment]
Thanks for the detailed report! 
Yes, we can provide a versions table of the LLRT version and QuickJS version. Maybe also async-runtime (`tokio`) version!

**Comment by p0wl** [comment]
Submitted a PR. How would you read the quickjs version? From the Cargo.toml? I couldn't find a way to access it (I don't know rust)

**Comment by richarddavison** [comment]
Fantastic, thanks for the PR! Reading `tokio` & `qjs` versions would require some gymnastics in build.rs to parse cargo.toml and and rquickjs submodule. I think it's a lot of work for small value. Your PR would suffice for most use cases for now 🥇
