### ISSUE TITLE
S3 GetObjectCommand is throwing an exception when used (Unexpected stream implementation, expect Blob or ReadableStream, got Uint8Array)

### ISSUE THREAD

**Issue by fredbonin** [awslabs/llrt#142]
## Description

When you try to download an object from S3, the S3Client throws an exception instead : 

```

2024-02-13T02:05:55.689Z	fc15815e-245d-4d51-8633-24deabb3699e	ERROR	    at Fr (llrt-chunk-sdk-GKKMFRJI.js:6:131)
--
at _g (@aws-sdk/client-s3:1:55290)
at <anonymous> (llrt-chunk-sdk-SXB3ZJRL.js:1:14739)
2024-02-13T02:05:55.689Z	fc15815e-245d-4d51-8633-24deabb3699e	ERROR	{  errorType: 'Error',  errorMessage: 'Unexpected stream implementation, expect Blob or ReadableStream, got Uint8Array
Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.',  stackTrace: [ '    at Fr (llrt-chunk-sdk-GKKMFRJI.js:6:131)', '    at _g (@aws-sdk/client-s3:1:55290)', '    at <anonymous> (llrt-chunk-sdk-SXB3ZJRL.js:1:14739)', '' ],  requestId: 'fc15815e-245d-4d51-8633-24deabb3699e'}
```

## To reproduce

1) Deploy the stack in `llrt/example/infrastructure` using CDK
2) Access the URL : https://API_GW/llrt-s3
3) Replace the PutObjectCommand in  : `llrt/example/functions/src/v3-s3.mjs` with a GetObjectCommand like below
```
    s3Client.send(
      new GetObjectCommand({
        Bucket: process.env.BUCKET_NAME,
        Key: "<KEY_OF_FILE_UPLOADED_AT_STEP_2>",
      })
    ),
```
4) Bug you will see the exception above.

**Comment by austinmik10** [comment]
How I got my lost funds recovered in binary options investment, through the help of Bruce David I have been in a deep shit all this while I almost lost all I have been investing from day one, I tried all I could to remain unbeatable I never gave up, sometime ago I was referred by a friend to one Mr David for assistance with his master class intelligence and strategy I'm able to make $10,000 weekly and also recovered all my lost funds. I'm so happy. If you need his help you can contact him through his email [brucedavid004@gmail.com](mailto:brucedavid004@gmail.com) or  Visit Texaco Recovery
https://www.facebook.com/profile.php?id=61550299165926
