### ISSUE TITLE
Coverage recording

### ISSUE THREAD

**Issue by pfumagalli** [awslabs/llrt#144]
Is there a way to save code coverage details when running tests?

Under NodeJS the [env var](https://nodejs.org/api/cli.html#node_v8_coveragedir) `NODE_V8_COVERAGE` allows to save the V8 coverage, [Bun](https://bun.sh/docs/test/coverage), and [Deno](https://docs.deno.com/runtime/manual/basics/testing/coverage) both have a `--coverage` flag.

Would be great to have this also in LLRT. That said, I don't see any support in QuickJS, and instrumenting code _(a-la NYC/Istanbul)_ can be a bit of a hassle...

**Comment by richarddavison** [comment]
Yes it would be a nice feature!  But you are correct. There is very little instrumentation support in QuickJS, so adding support for it would require some non-trivial modification of the engine.
