### ISSUE TITLE
Are dependencies via lambda layers (e.g. Sentry) supposed to work?

### ISSUE THREAD

**Issue by p0wl** [awslabs/llrt#147]
We are using Sentry via a lambda layer in our application. See [here](https://docs.sentry.io/platforms/node/guides/aws-lambda/layer/). Layer arn: `arn:aws:lambda:eu-central-1:943013980633:layer:SentryNodeServerlessSDK:193`

The @sentry/serverless package is imported in our app like this:
`import { AWSLambda } from '@sentry/serverless';` / `var import_serverless = require("@sentry/serverless");` (after esbuild)

In our cdk build step, we exclude it via external modules:
```
externalModules: ['@sentry/serverless', ...]
```

but with LLRT, we get the following error when the lambda function is invoked:

```
ERROR	{
  errorType: 'ReferenceError',
  errorMessage: 'Error resolving module '@sentry/serverless' from '/var/task/index.mjs'',
  stackTrace: [ '' ]
}
```

If I remove @sentry/serverless from externalModules, the error disappears, so I guess either the layer is not getting picked up by LLRT.

**Comment by richarddavison** [comment]
Dependencies in layers does not work. You would have to bundle with your sources:
https://github.com/awslabs/llrt?tab=readme-ov-file#using-node_modules-dependencies-with-llrt
I would suspect that @sentry might use some unsupported APIs tho 🤔
