### ISSUE TITLE
process.hrtime.bigint() returns result inconsistent with node.js runtime

### ISSUE THREAD

**Issue by floydspace** [awslabs/llrt#150]
```js
// teat.js
console.log(process.hrtime.bigint());
```
<img width="476" alt="image" src="https://github.com/awslabs/llrt/assets/5180700/fb0c7c6a-118e-4480-bb5d-93573f51e518">

https://github.com/awslabs/llrt/blob/b01b7aab8a8182b05be57cfa297235250e58817f/src/process.rs#L40

**Comment by richarddavison** [comment]
Resolution should be the same, right now is micros rather than nanos. So we'll need to fix it!
