### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by kaihendry** [awslabs/llrt#159]
Hi, how did you create these?

<img src=https://github.com/awslabs/llrt/raw/main/benchmarks/llrt-ddb-put.png>

Was it `make bench`? I can't get that to work on my MBP. https://gist.github.com/kaihendry/02f060a9499582fc0e598eb0eeb31643

My goal was to compare my project without llrt and then [incorporate llrt](https://github.com/awslabs/llrt/issues/149) and run the benchmark again. So ideally it's some github action or something.

**Comment by richarddavison** [comment]
Hi! It was not `make bench`. The screenshot here is from an internal (soon to be open source) tool to measure Lambda Latency via CLI.
You can simulate the same effect by deploying the example stack (`make release-arm64 && make deploy`) and using any http benchmarking tool, for example using https://github.com/hatoo/oha
`oha -c 100 -z 30s https://{YOUR_ID}.execute-api.eu-north-1.amazonaws.com/llrt`

And then view metrics inside of CloudWatch insights:
```sql
filter @type = "REPORT"
| parse @log /\d+:\/aws\/lambda\/(?<function>[-\w\d]+)/
| stats
count(*) as invocations,
pct(@duration+greatest(@initDuration,0), 0) as p0,
pct(@duration+greatest(@initDuration,0), 25) as p25,
pct(@duration+greatest(@initDuration,0), 50) as p50,
pct(@duration+greatest(@initDuration,0), 75) as p75,
pct(@duration+greatest(@initDuration,0), 90) as p90,
pct(@duration+greatest(@initDuration,0), 95) as p95,
pct(@duration+greatest(@initDuration,0), 99) as p99,
group by function, ispresent(@initDuration) as coldstart
| sort by function, coldstart
```
