### ISSUE TITLE
should platform be node or browser when using esbuild?

### ISSUE THREAD

**Issue by tmokmss** [awslabs/llrt#163]
Hi, I found In the current README, there are seemingly contradicting descriptions about bundling:

> All dependencies should be bundled for a browser platform

> esbuild index.js --platform=node --target=es2020 --format=esm --bundle --minify --external:@aws-sdk --external:@smithy --external:uuid

so which [`--platform` option](https://esbuild.github.io/api/#platform) (`node` or `browser`) should we set when using esbuild?

**Comment by floydspace** [comment]
Using `browser` or `neutral` will not work, because `esbuild` would not be able to find the built-in node modules in `node_modules`.
you must use `node`

**Comment by richarddavison** [comment]
`node`. I'll update the docs!

**Comment by richarddavison** [comment]
Actually this depends on what you're shipping. To use SDKs that are not embedded, you must target browser (will use fetch SDK client). So a safe bet is target browser and use/mark `node externals`
