### ISSUE TITLE
`signal` property missing from `Request` object

### ISSUE THREAD

**Issue by jabrks** [awslabs/llrt#182]
Forgive me as I was unsure if `Request` was covered by `fetch` in the compatibility matrix or not, but I noticed when creating a new `Request` object with an `AbortSignal` that the same `AbortSignal` is not then accessible from the `signal` property of the newly-created object

```js
// index.js
const controller = new AbortController();
const req = new Request('http://localhost/', { signal: controller.signal });

console.log(req.signal);
```

```bash
node index.js
# AbortSignal { aborted: false }
```

```bash
./llrt index.js
# undefined
```

**Comment by richarddavison** [comment]
We've been working on increasing the WHATWG/WinterCG Fetch compatibility. What's still missing is AbortController and Readable/Writable streams. The AbortController support is relatively straight forward to implement as it's a pretty light API.

`AbortSignal` is currently only stubbed in LLRT and has no effect. This is something we're working on but PR's are welcome:
https://github.com/awslabs/llrt/blob/1ece463450aaab989a4ecd612caf34606e1c86ef/src/events.rs#L378

**Comment by jabrks** [comment]
I'd completely missed that `AbortController` was stubbed. Thanks for confirming that this is on the roadmap
