### ISSUE TITLE
Invalid JSON serialization of dates in v0.1.4+

### ISSUE THREAD

**Issue by andyneville** [awslabs/llrt#183]
Since version v0.1.4 and onward through the current (v0.1.7) release, JSON serialization of objects that include a Date property result in improperly formatted JSON, with duplicate rendering of keys.

Using v0.1.7-beta release on MacOS ARM64 (and confirmed in Lambda ARM64):

date-test.js
```js
const value = {
  date: new Date()
}

console.log(JSON.stringify(value))
```

Expected output: `{"date":"2024-02-20T17:13:17.908Z"}`
Received output: `{"date":"date":"2024-02-20T17:14:06.578Z"}` which is invalid JSON (note the doubling of the `"date"`)

Tested backwards and this appears to work correctly in v0.1.3, and to be broken in subsequent versions
```bash
% ./llrt-0.1.3 -v && ./llrt-0.1.3 date-test.js
LLRT (darwin arm64) 0.1.3-beta
{"date":"2024-02-20T17:15:41.779Z"}
% ./llrt-0.1.4 -v && ./llrt-0.1.4 date-test.js
LLRT (darwin arm64) 0.1.4-beta
{"date":"date":"2024-02-20T17:15:51.029Z"}
% ./llrt-0.1.5 -v && ./llrt-0.1.5 date-test.js
LLRT (darwin arm64) 0.1.5-beta
{"date":"date":"2024-02-20T17:15:57.396Z"}
% ./llrt-0.1.6 -v && ./llrt-0.1.6 date-test.js
LLRT (darwin arm64) 0.1.6-beta
{"date":"date":"2024-02-20T17:16:03.466Z"}
% ./llrt-0.1.7 -v && ./llrt-0.1.7 date-test.js
LLRT (darwin arm64) 0.1.7-beta
{"date":"date":"2024-02-20T17:16:08.797Z"}
 ```

And just for comparison, how it works in node:
```bash
% node -v && node date-test.js
v20.11.0
{"date":"2024-02-20T17:19:23.854Z"}
```

**Comment by richarddavison** [comment]
Thanks for the detailed report and reproducible. Will take a look!
