### ISSUE TITLE
Bundle AWS SDK V3 packages in Lambda layer

### ISSUE THREAD

**Issue by jagonzalr** [awslabs/llrt#194]
Hello,

Is it possible to bundle the AWS SDK packages into a Lambda layer and connect it to the Lambda, instead of bundling the node_modules into the Lambda itself?

**Comment by richarddavison** [comment]
Hi there! The AWS SDK packages are already included in the binary itself so you can simply mark them as external in your bundler. Or maybe I misunderstand, what are you trying to do?

**Comment by jagonzalr** [comment]
Hi @richarddavison, sorry for the vagueness.

So I know LLRT includes some AWS packages like `@aws-sdk/client-cognito-identity` but in my case I need `@aws-sdk/client-cognito-identity-provider`. So what I did was create 2 lambda layers, one with the provided zip for LLRT and another one that includes `@aws-sdk/client-cognito-identity-provider`, and attached them to my Lambda.

If I run the Lambda it returns with an error that it couldn't find `@aws-sdk/client-cognito-identity-provider` package 😞 

Any guidance on this use case? Is it possible to use LLRT and any other layers together?

**Comment by richarddavison** [comment]
Hi again. You should bundle the `@aws-sdk/client-cognito-identity-provider` with your code and mark all other SDKs as external. We should create an example how to do this 👍

**Comment by jagonzalr** [comment]
Ok so package the node_modules into the code and no support for other layers attached to the Lambda at the moment?

**Comment by richarddavison** [comment]
Correct 🙂

**Comment by jagonzalr** [comment]
Ok perfect, thanks for clarifying 😄
