### ISSUE TITLE
Error unable to load module 'url'

### ISSUE THREAD

**Issue by bw-sonph** [awslabs/llrt#195]
Currently I use esbuild to build the main.js file, however it seems the url module is not supported and an error appears as below. Please help.

Response
{
  "errorType": "ReferenceError",
  "errorMessage": "Error resolving module 'url' from '/var/task/dist/main.js'",
  "stackTrace": [
    ""
  ]
}

**Comment by richarddavison** [comment]
URL is available on global scope. Do you have problems with a dependency or in your own code?

**Comment by bw-sonph** [comment]
I have a test.ts file

```nodejs
import url from 'node:url'

export const handler = async (event: any, context: any) => {
   const adr = 'http://localhost:8080/default.htm?year=2017&month=february';
   const q = url.parse(adr, true);

   console.log(q);
};
```

when using the command below
```cmd
esbuild test.ts --platform=node --target=es2020 --outdir=dist --format=esm --bundle --minify --external:@aws-sdk --external:uuid 
```

to build into a test.js file with the following content

```js
import o from"url";var c=async(r,a)=>{let t=o.parse("http://localhost:8080/default.htm?year=2017&month=february",!0); console.log(t)};export{c as handler};
```

Then deploy to the lambda with Runtime = Amazon Linux 2023 and the boostrap file is llrt-lambda-x64.zip
<img width="1335" alt="Screenshot 2024-02-24 at 9 46 00" src="https://github.com/awslabs/llrt/assets/39482942/52bf0539-97e9-4bfb-a8f5-5ea67759737a">



then get the following error

<img width="1344" alt="Screenshot 2024-02-24 at 9 46 14" src="https://github.com/awslabs/llrt/assets/39482942/62ddf8c9-de8a-450c-860f-c8a9c0dafb1c">

```json
{
   "errorType": "ReferenceError",
   "errorMessage": "Error resolving module 'url' from '/var/task/index.mjs'",
   "stackTrace": [
     ""
   ]
}
```

It seems the module 'url' cannot be loaded.

**Comment by richarddavison** [comment]
I see. You can use `new URL(adr)` instead without importing anything 👍

**Comment by bw-sonph** [comment]
Thank you for your help. 
Actually I'm building a lambda using nestjs. Build successfully and run in lambda but get the same error.

```
{
   "errorType": "ReferenceError",
   "errorMessage": "Error resolving module 'url' from '/var/task/index.mjs'",
   "stackTrace": [
     ""
   ]
}
```

**Comment by richarddavison** [comment]
Ah right, we probably need to add it as a module.

**Comment by richarddavison** [comment]
Tracked by: https://github.com/awslabs/llrt/issues/195
