### ISSUE TITLE
fs.readdir withFileTypes:true returns useless fs.Dirent objects

### ISSUE THREAD

**Issue by monsterkodi** [awslabs/llrt#198]
while llrt recognizes the withFileTypes:true option of fs.readdir calls,
the returned objects are quite useless.
in node and bun, you receive some objects that let you determine the type (directory or file).
llrt just provides the name of the entry.

it would be nice if at least the type of the node would be provided.

**Comment by richarddavison** [comment]
This is already implemented, see:
https://github.com/awslabs/llrt/blob/7b6252bace1026bbbe4e5e1385cd1399d225ff95/tests/fs.test.ts#L16
what issues are you facing?

**Comment by monsterkodi** [comment]
hello Richard,
thanks for your fast reply.
you are right, the returned objects provide an `isFile` method.
i was testing it with `isDirectory` instead of `isFile`, probably because it is listed higher in the documentation of node's `fs.Dirent`.
maybe providing `isDirectory` as well would be nice?
anyways, the issue is not really an issue, so i am closing it.
