### ISSUE TITLE
Base image for container packaged lambda functions?

### ISSUE THREAD

**Issue by JonHolman** [awslabs/llrt#217]
Will there be a container base image that we can use instead of public.ecr.aws/lambda/nodejs:20 ?

**Comment by richarddavison** [comment]
We'll add a Lambda OCI (Container) example as well :)

**Comment by JonHolman** [comment]
Thanks!  I was playing around with copying bootstrap into the al2023 provided image, but got lost adding node_modules.

**Comment by richarddavison** [comment]
@JonHolman it would be helpful if you could give a bit of context of what are you trying to do? Why are you looking to package LLRT in a container?

**Comment by JonHolman** [comment]
@richarddavison sure.  I think having a container option would assist in making LLRT available for more use cases.  In what I am trying to do right now and would like to evaluate if LLRT is an option and would improve performance.  I'm trying to run llama.cpp with a small LLM within a lambda function.  My simple WIP can be seen at https://github.com/JonHolman/wip-sam-node-llama-cpp

**Comment by richarddavison** [comment]
@JonHolman when we release a new version, you should be able to deploy a container optimized version of LLRT. This should have significantly lower cold starts compared with adding the once that exists today.

**Comment by richarddavison** [comment]
Released in https://github.com/awslabs/llrt/releases/tag/v0.1.11-beta
