### ISSUE TITLE
`llrt` as AWS-`managed` runtime

### ISSUE THREAD

**Issue by o-alexandrov** [awslabs/llrt#237]
Please consider to offer `llrt` as Lambda AWS-managed runtime to simplify/increase adoption.
- I’m not sure whether this repo is the right place to ask for it though

**Comment by o-alexandrov** [comment]
@richarddavison @nikp 
Sorry for bothering you.
Do you have plans to offer provided by AWS LLRT runtime on Lambda?

**Comment by richarddavison** [comment]
Hi @o-alexandrov. No worries. Sorry to say that we're still can't share any news regarding provided LLRT. We're right now working hard on a more complete WinterCG API. Thanks for staying patient and your continued interest in this project :)
