### ISSUE TITLE
Error resolving module '/var/task/@smithy/querystring-builder'

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#247]
Hello,
I am developing an application using `@aws_sdk/s3-request-presigner` with Lambda integrated into API Gateway.

I tried to run the application using `@aws_sdk/s3-request-presigner` with `llrt`, but it doesn't work properly.

In the "Using AWS SDK (v3) with LLRT" section of the README, it is written that `@smithy` is bundled, but an error occurs that `@smithy/querystring-builder` cannot be resolved.

Do I need to exclude `@smithy` with the `--external` option of ESBUILD?

index.js:
```javascript
const { S3Client, GetObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');

exports.handler = async (event) => {

  const getParams = {
    Bucket: 's3-sample-bucket',
    Key: 'sample.jpg',
  };

  const client  = new S3Client(getParams);
  const command = new GetObjectCommand(getParams);
  const downloadUrl = await getSignedUrl(client , command, { expiresIn: 60 });

  return {
    statusCode: 307,
    headers: {
      location: downloadUrl,
    }
  };
};
```

ESBUILD:
```
esbuild index.js --platform=node --target=es2020 --format=esm --bundle --external:@aws-sdk/client-s3 --external:@smithy --external:uuid --outfile=./dist/index.mjs
```

error message:
```
2024-03-07T08:40:38.174Z	n/a	ERROR	ReferenceError: Error resolving module '/var/task/@smithy/querystring-builder' from '/var/task/index.mjs'
  at node_modules/@aws-sdk/util-format-url/dist-cjs/index.js (/var/task/index.mjs:39:38)      at __require2 (/var/task/index.mjs:10:17)      at node_modules/@aws-sdk/s3-request-presigner/dist-cjs/index.js (/var/task/index.mjs:736:34)      at __require2 (/var/task/index.mjs:10:17)      at index.js (/var/task/index.mjs:866:28)      at __require2 (/var/task/index.mjs:10:17)      at <anonymous> (/var/task/index.mjs:884:16)

```
P.S.
My native language is Japanese. This sentence was translated by AI.

**Comment by richarddavison** [comment]
Thanks for the report! It looks like we need to include `@smithy/querystring-builder` to the included bundle. Adding custom clients that are not embedded may produce duplicate code as your bundler does not know what's included in LLRT. I'll update the documentation and provide a fix so the included `@smithy` modules can work with non embedded clients

**Comment by richarddavison** [comment]
Hi @nabetti1720 I have now submitted a PR that should fix your issues. You should now be able to import `@aws-sdk/s3-request-presigner` since it is now included with the runtime.
