### ISSUE TITLE
AbortController

### ISSUE THREAD

**Issue by richarddavison** [awslabs/llrt#248]
https://developer.mozilla.org/en-US/docs/Web/API/AbortController

No-op implementation is in:
https://github.com/awslabs/llrt/blob/36f8030a2c8194c84c9db1c37455ea3cd103ef97/src/events.rs#L378

Also see https://github.com/awslabs/llrt/issues/182
```[tasklist]
### Tasks
- [x] Add signal and abort handling to Fetch API
```

**Comment by MozarellaMan** [comment]
Hi, I'd like to try working on this - just to clarify, wouldn't this include implementing `AbortSignal`? Or could it just return the no-op AbortSignal?

```rust
#[rquickjs::methods]
impl<'js> AbortController<'js> {
    #[qjs(constructor)]
    fn new() -> Self {
        Self {
            signal: AbortSignal
        }
    }

    #[qjs(get)]
    fn signal(&self) -> AbortSignal {
        self.signal
    }

    fn abort(reason: Opt<Value<'js>>) {

    }
}
```
I started with this but not sure how useful it would be without methods like `abort(reason)` on `AbortSignal`

**Comment by richarddavison** [comment]
Hi @MozarellaMan! Thanks for looking into this. That's right, we need to have the actual implementation. For instance if signal is passed to fetch we should abort the request if signal is set. But it would suffice to just have the AbortController and signal classes and I'll can sort out the rest :)

**Comment by MozarellaMan** [comment]
Nice! I'll see how far I get with stubbing out stuff. One other question, I'm running into an error with building, specifically with [generate_compression_dictionary](https://github.com/awslabs/llrt/blob/8bcbfe4fe893262c280bcd46bd4820f0c1267925/build.rs#L218) in `build.rs`. I'm not exactly sure what this is doing to be honest. But I get this error which I assume is from `zstd`
```
 --- stderr
  !  Warning : nb of samples too low for proper processing ! 
  !  Please provide _one file per sample_. 
  !  Alternatively, split files into fixed-size blocks representative of samples, with -B# 
  Error 14 : nb of samples too low
```
I'm building this on M1 Mac so I'm guessing it might have to do with file system stuff? Is this build step necessary for development - could I comment it out for now?

**Comment by richarddavison** [comment]
> Nice! I'll see how far I get with stubbing out stuff. One other question, I'm running into an error with building, specifically with [generate_compression_dictionary](https://github.com/awslabs/llrt/blob/8bcbfe4fe893262c280bcd46bd4820f0c1267925/build.rs#L218) in `build.rs`. I'm not exactly sure what this is doing to be honest. But I get this error which I assume is from `zstd`
> 
> ```
>  --- stderr
>   !  Warning : nb of samples too low for proper processing ! 
>   !  Please provide _one file per sample_. 
>   !  Alternatively, split files into fixed-size blocks representative of samples, with -B# 
>   Error 14 : nb of samples too low
> ```
> 
> I'm building this on M1 Mac so I'm guessing it might have to do with file system stuff? Is this build step necessary for development - could I comment it out for now?

The error happens because JS source files are missing. We should check for this in build.rs and give a better error message. `make js` or `node build.mjs` should fix this :)

**Comment by richarddavison** [comment]
Fixed in https://github.com/awslabs/llrt/pull/271
