### ISSUE TITLE
Output of console.log is divided in CloudWatch Logs

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#255]
Hello,
I sometimes write the following code in Lambda to check the contents of an `event` from API Gateway.

```javascript
console.log('Received event:', JSON.stringify(event, null, 2));
```

When this code is executed in `node.js`, it is displayed collapsed into one line in CloudWatch Logs, but when executed in `llrt`, it is output divided by line breaks.

node.js:
![image](https://github.com/awslabs/llrt/assets/7500514/f3ed711b-bf47-45ac-99f0-cb581faeb61f)

llrt:
![image](https://github.com/awslabs/llrt/assets/7500514/ddae9c68-a575-49c7-9f7b-9940be277ff3)

I understand that `llrt` has a different implementation from `node.js`, but is it possible to improve this?

**Comment by richarddavison** [comment]
Yes. This is a bug. Thanks for reporting 👌
