### ISSUE TITLE
README benchmark linking correct file?

### ISSUE THREAD

**Issue by perpil** [awslabs/llrt#265]
In looking at the benchmarks in the README, the numbers for nodejs20 seem too high for a ddb put, are you still using this [code](https://github.com/awslabs/llrt/blob/main/example/functions/src/v3-lib.mjs) as referenced or something else in [this directory](https://github.com/awslabs/llrt/tree/main/example/functions/src)?

Secondly, out of curiosity, are you setting environment variables?  I noticed doing some testing today that due to Lambda making additional calls to sts:AssumeRole and kms:Decrypt when you've set environment variables, it adds 15-34ms to the E2E latency on coldstarts.

**Comment by richarddavison** [comment]
Hi @perpil! Yes, this is still the case. However, you can get the cold start number lower on Node if you bundle, minify and tree-shake to only ship code that's actually being used. Even when doing so, cold starts on LLRT will be 4-7x lower. Also note that to measure a cold start, you have to look at `Init duration` + `Duration` as that is the total time it took for the Lambda function to process the event. Additionally, you have some latency when Lambda is downloading your code and starting the VM. Regarding environment variables I could not see any difference in e2e latency with or without environment variables. How did you observe this?

**Comment by perpil** [comment]
Thanks Richard. So for node20, you are using the aws v3 sdk on disk?  What is in your .zip file, just [this](https://github.com/awslabs/llrt/blob/main/example/functions/src/v3-lib.mjs)?  Maybe using at least 512MB and minify + bundling has left me blind to how bad it is when you don't.

The env variable latency is only on coldstarts.  To test the env variable latency, I created a Lambda that invoked a Lambda with and without environment variables. The function measured the latency of the invocations. To make sure making the ssl connection wasn't adding overhead, I made a call to lambda to prime the client, enabled connection reuse and randomized the order of the invocations. Every time the function without environment variables was faster.  It was 23 ms faster on average.  If you look in CloudTrail, you'll see an extra `sts:AssumeRole` and `kms:Decrypt` when you have environment variables vs. when you don't.  The time to do this isn't included in the Init Duration but shows up in the E2E time.  Here's the code I was using.  I ran this at a 3 hour interval for a day.

```javascript
import { LambdaClient, InvokeCommand, LogType } from "@aws-sdk/client-lambda";

const client = new LambdaClient({
  region: process.env.AWS_REGION,
  maxAttempts: 1,
});

const invoke = async (funcName, payload = {}) => {
  const command = new InvokeCommand({
    FunctionName: funcName,
    Payload: JSON.stringify(payload),
    LogType: LogType.None,
  });
  let start = Date.now();
  const { Payload } = await client.send(command);
  let latency = Date.now() - start;
  let { requestId, coldstart } = JSON.parse(
    JSON.parse(Buffer.from(Payload).toString()).body
  );
  return {
    funcName,
    requestId,
    coldstart,
    latency,
  };
};

export const handler = async (event, context) => {
  //prime the http client
  try {
    await invoke("non-existent");
  } catch (e) {}

  //randomize order
  let funcs = ["Function", "FunctionWithEnv"];
  if (Math.random() < 0.5) {
    funcs = funcs.reverse();
  }

  //invoke
  for (const f of funcs) {
    console.log(await invoke(f));
  }
};
```

**Comment by richarddavison** [comment]
> Thanks Richard. So for node20, you are using the aws v3 sdk on disk? What is in your .zip file, just [this](https://github.com/awslabs/llrt/blob/main/example/functions/src/v3-lib.mjs)? Maybe using at least 512MB and minify + bundling has left me blind to how bad it is when you don't.

Yes that's it. 

> The env variable latency is only on coldstarts. To test the env variable latency, I created a Lambda that invoked a Lambda with and without environment variables

Nice observation! You are also correct! it might add some additional latency(end-2-end) for cold starts due to decrypting from kms :)
