### ISSUE TITLE
Dynamic require of \"@smithy/protocol-http\" is not supported

### ISSUE THREAD

**Issue by jagonzalr** [awslabs/llrt#268]
Hello,

Using the latest [llrt-lambda-arm64.zip](https://github.com/awslabs/llrt/releases/download/v0.1.11-beta/llrt-lambda-arm64.zip) layer bundle on some of my Lambda functions are working great.

Now I have a use case where I need to have `mediaconvert` or `transcribe` package. What I did was bundle the packages into my code. I'm getting `Dynamic require of \"@smithy/protocol-http\" is not supported`.

Any ideas on how to fix that?

Running on Node 18

**Comment by richarddavison** [comment]
Hi @jagonzalr, thanks for the report. We will add samples on how to add SDKs that are not embedded. Tacked by https://github.com/awslabs/llrt/issues/283

**Comment by richarddavison** [comment]
Closing now as tracked by https://github.com/awslabs/llrt/issues/283
