### ISSUE TITLE
No rule to make target 'llrt-linux-x86_64.zip'

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#274]
Hello,
I am currently working on being able to build correctly in a `Windows WSL2` environment.

However, when I run the `make release`, I get the following error:
```bash
$ uname -r
5.15.146.1-microsoft-standard-WSL2
$ make release
make: *** No rule to make target 'llrt-linux-x86_64.zip', needed by 'release'.  Stop.
```
In the case of `Windows WSL2`, the `OS` is determined to be `Linux`. Furthermore, since the return value of `uname -m` is `x86_64`, it does not fit any of the patterns assumed by MAKEFILE.

```bash
$ uname -m
x86_64
```

I already have a plan to make the build succeed by converting the `ARCH`, so I will make a Pull Request later.

PS
I have tried to fix it with PR #275 but it seems to break CI.
Is there a better fix?

**Comment by richarddavison** [comment]
Thank you! Fixed by https://github.com/awslabs/llrt/pull/275
