### ISSUE TITLE
Migrate to C?

### ISSUE THREAD

**Issue by Symbitic** [awslabs/llrt#277]
In honor of the QuickJS engine at the heart of this, should it at least be considered switching from Rust to C?

**Comment by richarddavison** [comment]
Hi @Symbitic!
There are a couple of reasons why we used Rust over C, the biggest ones are:
* Memory safety
* Tooling & ecosystem
* Productivity & standard library
* Performance comparable with C, C++
* Error handling & other desirable language features

Hope this sheds some light why we use Rust
