### ISSUE TITLE
Invalid JSON serialization of 'undefined' values

### ISSUE THREAD

**Issue by andyneville** [awslabs/llrt#286]
Using version 0.1.11-beta, serializing an object containing an undefined property results in invalid JSON:

```js
const value = {
  a: undefined,
  b: '123'
};

console.log(JSON.stringify(value));
```

Expected output: `{"b":"123"}`
Actual output (LLRT): `{,"b":"123"}` which is invalid JSON because of the *extraneous comma*.

Running this same example file in Node.js creates the expected output of `{"b":"123"}`

**Comment by andyneville** [comment]
With further testing I just noticed this only occurs when the undefined property is the first property, if you swap the order then the JSON serialization is what you would expect. Only when the first property is undefined does it appear to leave the extra comma in place

**Comment by nabetti1720** [comment]
Hi @andyneville, I was curious so I verified it too.

I can certainly reproduce it in the 0.1.11-beta deliverables.

```bash
$ ./llrt -e "console.log(JSON.stringify({a: undefined, b: '123', c: undefined}));"
{,"b":"123"}
```

But it is resolved in a manual build from the latest code.

```bash
$ ./llrt -e "console.log(JSON.stringify({a: undefined, b: '123', c: undefined}));"
{"b":"123"}
```

Looking at the commit log, it seems that PR #263 is probably the improvement.
If this is correct, the next version should be improved.
Let's look forward to the next release together!

**Comment by richarddavison** [comment]
Yes, this was a bug patched in https://github.com/awslabs/llrt/pull/263
Will create a new release today!

**Comment by richarddavison** [comment]
@andyneville Sorry for the delay but it's released now:
https://github.com/awslabs/llrt/releases/tag/v0.1.12-beta
