### ISSUE TITLE
JSON.stringify turns objects with functions into invalid JSON

### ISSUE THREAD

**Issue by yspreen** [awslabs/llrt#295]
I'm getting 502 errors with `Runtime exited without providing a reason Runtime.ExitError` and no other info.

Is `decodeURIComponent` the culprit?

I'm also trying to run `process.hrtime()[1]` in order to get a sub-ms timer but that one surprisingly doesn't cause a crash.

**Comment by yspreen** [comment]
adding these lines causes a crash:

```
  const awsRequestId = JSON.parse(
    decodeURIComponent(req.headers["x-apigateway-context"] as string)
  ).awsRequestId.replace(/(...).*(...)/, "$1…$2");
```

**Comment by yspreen** [comment]
maybe JSON encoding is to blame. not sure. this definitely crashes a handler:

```ts
JSON.parse(decodeURIComponent(encodeURIComponent(JSON.stringify(context))))
```

**Comment by yspreen** [comment]
it appears the bug is in the JSON encoder.

this line 
```
getRemainingTimeInMillis: [function: getRemainingTimeInMillis],
````

turns into

```
"getRemainingTimeInMillis":,
```

which is not valid JSON.

**Comment by richarddavison** [comment]
Its most likely related to this issue: https://github.com/awslabs/llrt/pull/263
I'm creating a new release today

**Comment by richarddavison** [comment]
@yspreen released now:
https://github.com/awslabs/llrt/releases/tag/v0.1.12-beta
