### ISSUE TITLE
Require does not work with the `node` prefix (i.e. : node:console)

### ISSUE THREAD

**Issue by fredbonin** [awslabs/llrt#309]
When using require with the `node:` prefix, LLRT will not find the module.

To reproduce : 

```
  let {Console} = require("node:console");
  const consoleObj = new Console({
    stdout: process.stdout,
    stderr: process.stderr,
  });
```

This causes issues with Powertools (#251)

**Comment by richarddavison** [comment]
Fixed in https://github.com/awslabs/llrt/pull/310
