### ISSUE TITLE
Publishing LLRT as a crate

### ISSUE THREAD

**Issue by KaanMol** [awslabs/llrt#319]
Hey all!

I'm working on adding a JavaScript runtime scripting to my Rust app. I started with Deno because it's broken down into crates, making it easy to use only what I need. This setup works well for me.

I'm looking at AWS's LLRT now, thinking it might give my app a performance boost. But it looks like LLRT isn't packaged in a way that lets me easily drop it into my Rust project.

I'm wondering if there are plans to make LLRT more modular, like Deno, for easier use in Rust apps. Also, I'm open to contributing to this effort when I have time. Is this something you'd be interested in?

Thanks for any info or suggestions you can provide!

**Comment by kaanmol-cpi** [comment]
@richarddavison I have thought of that, but I also need quite a few extensions like the http, crypto etc, and that was the reason I looked at the full Deno runtime, which didn't have the best performance. 
Besides that, if someone happened to be using rquickjs, it would be great if they could for example just take LLRT's crypto module for example :)

**Comment by KaanMol** [comment]
@richarddavison I have thought of that, but I also need quite a few extensions like the http, crypto etc, and that was the reason I looked at the full Deno runtime, which didn't have the best performance.
Besides that, if someone happened to be using rquickjs, it would be great if they could for example just take LLRT's crypto module for example :)

**Comment by richarddavison** [comment]
Oh that's right. Feel free to take this on when time permits. The modules are pretty independent. I recon that letting users opt in to modules using a builder pattern in VM would be better than having a million feature flags. Maybe also have an abstraction to register custom modules or global functions? 95% of what you'll need for this is in `vm.rs` :)

**Comment by gc-victor** [comment]
I created one using some parts of lltr, which was relatively easy.

> Maybe also have an abstraction to register custom modules or global functions?

It would be great to have Rust (rquickjs) and JS polyfills to register them in a runtime (vm) abstraction.

**Comment by KaanMol** [comment]
@richarddavison I saw that they were already pretty standalone indeed. Just wanted to make sure that if I would make this, it would be something you guys would be happy to merge in, instead of me maintaining a fork for myself

**Comment by gc-victor** [comment]
IMO, it should be something apart from lltr, but using their modules to start working on it would be helpful. I would create a `rquickjs-runtime` crate with the abstraction mentioned before and different modules using a similar naming like `rquickjs-fetch` and the same for JS libraries `rquickjs-whatever`.

**Comment by KaanMol** [comment]
I don't see it as that differently to be honestly, since in this case LLRT can be an executable as well as a library, but after making it, these things can always be accomplished down the line.

**Comment by gc-victor** [comment]
Some parts of the LLRT code depend on AWS, and it is not currently available as a library. With my proposal, LLRT can use the same modules as your runtime, and many other people can create their own, so you don't have to maintain that much code by yourself. Maybe I'll make it. :thinking: Would you be interested in collaborating?

**Comment by KaanMol** [comment]
@gc-victor I have been glancing over the code quickly, I don't see much besides main.rs the logging part that is really AWS dependant. My idea was just to create a lib.rs to start with and implement the parts that vm.rs implements as a start honestly. The things I would make is not something that I would actually have to maintain, since they are just the same functions that get called in vm? 

I am not 100% sure how much time I have available and when, what would make collaborating a bit tricky I assume.

**Comment by richarddavison** [comment]
> @gc-victor I have been glancing over the code quickly, I don't see much besides main.rs the logging part that is really AWS dependant. My idea was just to create a lib.rs to start with and implement the parts that vm.rs implements as a start honestly. The things I would make is not something that I would actually have to maintain, since they are just the same functions that get called in vm?
> 
> I get where you want to go to with making LLRT dogfeed its own libraries, but for that it might be quite a lot of changes where I would prefer to start "easy" and look at how it would be possible to migrate the vm.rs file to consume the library over time.
> 
> I am not 100% sure how much time I have available and when, what would make collaborating a bit tricky I assume.

Yeah I think it should belong in here as `rquickjs` is already a crate with limited scope trying to stay within the engine- vs the runtime space. I do get the benefits tho, but we are deliberately trying to make this not to coupled with AWS. We only do so where we have a performance gain and try to feature gate this away (hint `no-sdk` & `lambda` flags).

Since this is still rather early in the development, focus has not been on providing a library so there is almost a complete lack of rust docs and most of the tests are in implemented in JS (so we can run the same tests with Node) which is also something that we which to improve. All help we can get is highly appreciated 👌

**Comment by gc-victor** [comment]
I agree that `rquickjs` has a different scope. I suggest creating a new repository, `rquickjs-runtime`, and using the same naming convention for the modules, such as `rquick-url` or `rquickjs-whatever`. I have previously created a small JS runtime, and would have appreciated having some modules I could add and use. It is what I did with LLRT, and within a couple of days, I had a runtime that met my needs. I would like to offer the same experience without having to copy and paste the code. You have done a great work here, the code was enough decoupled to do it easily. I really appreciate your work, and that you have share it as open source.

**Comment by KaanMol** [comment]
@gc-victor I am looking through it and I really think it should not be split up. 
For instance, when I tried splitting the `http` part up to its own crate, I had to create a utils/common/whatever crate with a major part of what's currently in the `src`, since most things are currently shared.  

The thing is, LLRT is really not that "much" code and my idea with this ticket was never to completely make everything standalone installable, but rather having at least the option to enable or disable the modules and execute JS from within a Rust app. 
By splitting this up further you'd just worsen the dev experience for devs working on the `LLRT` repo.

**Comment by KaanMol** [comment]
@richarddavison I am looking in to into making it a library, it doesn't look that hard. I had a few questions:
- Are you fine with me moving the modules like `http`, `fs` etc to its own `modules` folder, to make it more organized?;
- Is it okay if I creating something like a builder pattern as you suggested and modify vm/main to make them use that as well?;

**Comment by richarddavison** [comment]
> @richarddavison I am looking at making this a library, it doesn't look that hard. I had a few questions:
> 
> * Are you fine with me moving the modules like `http`, `fs` etc to its own `modules` folder, to make it more organized?;
> * Is it okay if I creating something like a builder pattern as you suggested and modify vm/main to make them use that as well?;

Yes! Go ahead. Also feel free to move out AWS specific stuff unless it affects perf. What do you think of `llrt-core` `llrt-lambda` etc. I haven't yet thought about how to deal with moving out AWS/Lambda specific logic. For instance, console has a `AWS_LAMBDA_MODE` and `LAMBDA_REQUEST_ID`. Feel free to give suggestions here. Maybe a `DefaultConsole` and `LambdaConsole` that implements a `JsConsole/RuntimeConsole` trait 🤔

**Comment by KaanMol** [comment]
> > @richarddavison I am looking at making this a library, it doesn't look that hard. I had a few questions:
> > 
> > * Are you fine with me moving the modules like `http`, `fs` etc to its own `modules` folder, to make it more organized?;
> > * Is it okay if I creating something like a builder pattern as you suggested and modify vm/main to make them use that as well?;
> 
> Yes! Go ahead. Also feel free to move out AWS specific stuff unless it affects perf. What do you think of `llrt-core` `llrt-lambda` etc. I haven't yet thought about how to deal with moving out AWS/Lambda specific logic. For instance, console has a `AWS_LAMBDA_MODE` and `LAMBDA_REQUEST_ID`. Feel free to give suggestions here. Maybe a `DefaultConsole` and `LambdaConsole` that implements a `JsConsole/RuntimeConsole` trait 🤔

Would you want to make `llrt-core` still a standalone executable or only available as a library? I saw the parts inside the `console`, `main` and a bit inside `vm` indeed. We could strip console to a sort of console utils and then build a `DefaultConsoleModule` and `LambdaConsoleModule` from that? Where `llrt-lambda` would just utilize the console parts to implement its own module and load that instead of the default one.

With that `llrt-lambda` would just register the `setRequestId` itself instead of inside the `llrt-core`.
Only thing I don't have a quick idea about is how to move the `ENV_LAMBDA_TASK_ROOT` part out of the `vm.rs` without passing some string as a param to the `Vm::new`.

**Comment by KaanMol** [comment]
I opened a PR btw, don't mind it too much at the moment. I just moved a part of the modules already to its own folder.  Tomorrow I can take a look at the Vm part

**Comment by richarddavison** [comment]
> With that llrt-lambda would just register the setRequestId itself instead of inside the llrt-core.
> I'm unsure how to abstract the handling of ENV_LAMBDA_TASK_ROOT from vm.rs without introducing a string parameter to Vm::new at the moment.

This is fine to move out as it only adds the `ENV_LAMBDA_TASK_ROOT` and `/opt` to `file_resolver` and `binary_resolver`.
It would make more sense to add these paths in as a Vec<Path> where LLRT looks for modules (could as well be `node_modules`). Another thing to pass to VM would be a custom resolver + loader

**Comment by KaanMol** [comment]
@richarddavison Could you take a look on the PR I made when you have time? I need to know if you prefer something along those lines or if I have to completely throw it around. In the comment of the PR I mentioned that the current way of registering the modules is not a good solution imo, but at the same time I dont know how I could do it else. Do you have an idea?

**Comment by brianjd** [comment]
Is the crate published?

**Comment by kaanmollaoglu-cpi** [comment]
@brianjd Not as far as I know. Cargo supports installing packages through [a Git url](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories). There is one problem with installing this repo like that though, I haven't had the opportunity to resolve that yet :(. The JS files aren't generated which throws a build error in the rust analyzer.

If you clone this repo and install the package through a [local path](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories), you can make it work. In the cloned LLRT repo you have to run `make js` (not sure if that's the only one with a fresh install atm). Then you should be able to use it without any hassle!

I hope to resolve the other bug soon once I have a bit more time😅

**Comment by KaanMol** [comment]
> Is the crate published?

@brianjd Not as far as I know. Cargo supports installing packages through [a Git url](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories). There is one problem with installing this repo like that though, I haven't had the opportunity to resolve that yet :(. The JS files aren't generated which throws a build error in the rust analyzer.

If you clone this repo and install the package through a [local path](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories), you can make it work. In the cloned LLRT repo you have to run `make js` (not sure if that's the only one with a fresh install atm). Then you should be able to use it without any hassle!

I hope to resolve the other bug soon once I have a bit more time😅

**Comment by brianjd** [comment]
Noted. thanks @KaanMol

**Comment by AugustinMauroy** [comment]
BTW there are a conflict in dep so it's impossible to use llrt modules for now:
```toml
[package]
name = "js-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs = "0.10.0"
llrt_modules = { git = "https://github.com/awslabs/llrt.git", package = "llrt_modules" }
tokio = "1"
```

```
    Blocking waiting for file lock on package cache
    Updating git repository `https://github.com/awslabs/llrt.git`
    Updating crates.io index
    Updating git repository `https://github.com/DelSkayn/rquickjs.git`
error: failed to select a version for the requirement `rquickjs = "^0.10.0"`
candidate versions found which didn't match: 0.11.0
location searched: Git repository https://github.com/DelSkayn/rquickjs.git
required by package `llrt_modules v0.7.0-beta (https://github.com/awslabs/llrt.git#d0a5da36)`
    ... which satisfies git dependency `llrt_modules` of package `js-runtime v0.1.0 (/Users/..../test-js)`
augu
````
