### ISSUE TITLE
Using crypto api

### ISSUE THREAD

**Issue by codingnuclei** [awslabs/llrt#333]
Hi,

I have been evaluating llrt with a preexisting lambda code base (which works as expected on node20) and seeing some sweet performance gains 🔥 🔥 

One problem I have stumbled across is with the crypto module.

My lambda running on llrt errors with:

`  errorType: 'MissingWebCrypto',
  errorMessage: 'An instance of the Crypto API could not be located',
`

I have narrowed it down to this lib https://github.com/MasterKale/SimpleWebAuthn  - and is throwing an error when this lib tries to access crypto:

https://github.com/MasterKale/SimpleWebAuthn/blob/ba7048cfd791cd9400871d008d21d1354543e2b3/packages/server/src/helpers/iso/isoCrypto/getWebCrypto.ts#L9

There is an issue on their github which helped me get some background on how they are accessing the crypto module
https://github.com/MasterKale/SimpleWebAuthn/issues/517

It looks to me like it should all just work on llrt but i could be very wrong.

Thoughts would be appreciated :)

**Comment by richarddavison** [comment]
Hi @codingnuclei! Crypto module has currently very limited support. Super cool to see you have nice perf gains! We're working on adding support for the full subtile crypto API! I'm closing this issue as it's being tracked by: https://github.com/awslabs/llrt/issues/184

**Comment by codingnuclei** [comment]
Thanks and keep up the good work!! ❤
