### ISSUE TITLE
Redirects are not handled in fetch()

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#340]
In other implementations (`node`, `bun`, etc.), when fetching the specified URI, a redirect is processed and the final response (status code 200) is returned, but in `llrt`, the redirect is not processed and status code 301 is returned.

Reproduction procedure:
```javascript
// fetch.js
const main = async () => {
  try {
    const response = await fetch('https://google.com');
    console.log(response.status);
    console.log(response.headers.get('location'));
  } catch(e) {
    console.log(e);
  }
}

main();
```

Execution results in `llrt`:
```bash
shinya@MBA2022M2 llrt-test % ./llrt fetch.js 
301
https://www.google.com/
```

Execution results in `bun`:
```bash
shinya@MBA2022M2 llrt-test % bun fetch.js 
200
null
```

**Comment by richarddavison** [comment]
Thanks for the well documented report. PR is welcome, want to take shot at it?
This could be implemented as looping over the response until no redirect header is present if `redirect` option is set to `follow` on the `Request` or fetch options.
https://github.com/awslabs/llrt/blob/d05da26103acc1fdf45afe15965ef05013e5f488/src/http/fetch.rs#L81

**Comment by nabetti1720** [comment]
Hi @richarddavison ,
I would love to work on this assignment if the opportunity arises :)
