### ISSUE TITLE
Console.log does not to print header values 

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#341]
`llrt` cannot display `fetch()` response headers in `console.log()`.

Reproduction procedure:
```javascript
// fetch.js
const main = async () => {
  try {
    const response = await fetch('https://www.google.com');
    console.log(response.status);
    console.log(response.headers.get('date'));
    console.log(response.headers);
  } catch(e) {
    console.log(e);
  }
}

main();
```

Execution results in `llrt`:
```bash
shinya@MBA2022M2 llrt-test % ./llrt fetch.js 
200
Sat, 20 Apr 2024 01:11:21 GMT
Headers { Symbol.iterator: undefined }
```

Execution results in `bun`:
```bash
shinya@MBA2022M2 llrt-test % bun fetch.js
200
Sat, 20 Apr 2024 01:11:28 GMT
Headers {
  "date": "Sat, 20 Apr 2024 01:11:28 GMT",
  "expires": "-1",
  // Other headers are also displayed.
}

```

**Comment by richarddavison** [comment]
Thanks for the bug report @nabetti1720! Keep 'em coming 🎉 We should fix so console prints iterators as well. Also we should fix so we don't print all keys,values for excessively large objects like we currently do.

**Comment by nabetti1720** [comment]
Hi @richarddavison ,
I have checked all the sources and it seems difficult for me to solve the problem.

https://github.com/awslabs/llrt/blob/d05da26103acc1fdf45afe15965ef05013e5f488/src/console.rs#L437-L449

In this case, we thought that L437 expected to get the list of keys in Headers, but in fact keys.len() returns zero.
Therefore, the decision in L440 is true, and the process of getting the list of methods appears to be working incorrectly.

In any case, stringify_value() is too complicated for me to fix...

**Comment by richarddavison** [comment]
Hi @nabetti1720.

Thanks for looking into this. The console implementation is quite complex and we should probably refactor this. I spent of lot of time building it to avoid recursion but since we often don't have so "deep" objects it has just complicated things. 

I'm looking into this, I need to investigate out how node is handing this, for instance if all iterators have their values printed or just a few specific ones.

**Comment by nabetti1720** [comment]
I don't know if this will be helpful...

It seems that node.js outputs all key/value without omission.
On the other hand, the implementation of deno is interesting.
```bash
```

**Comment by richarddavison** [comment]
Thanks for the info! I'm curios to see how this works in a more generic way.
I see now what Node does. It sets a special symbol on objects which gets executed if present on an object when running console.log:
https://nodejs.org/api/util.html#utilinspectcustom
So `Headers` has this symbol specified:
```javascript
[util.inspect.custom](depth, options) {
   options.depth ??= depth;
   return `Headers ${util.formatWithOptions(options, this[kHeadersList].entries)}`;
}
```

We need to apply a similar mechanism in LLRT:
```javascript
const customConsoleSymbol = Symbol.for('llrt.custom.console');
```

And then apply that to rust data structures for custom console handling

**Comment by nabetti1720** [comment]
I see, with this method, the console does not need to know the contents of the object to be displayed, and the object itself can be displayed in the format expected by the console.

It also seems to simplify the implementation on the console side.

This time it was the header that was targeted, but do other objects need to add Symbol in the same way? Or will there be a common implementation that outputs all keys/values and properties, and then override them if you want to customize them individually?

**Comment by richarddavison** [comment]
> I see, with this method, the console does not need to know the contents of the object to be displayed, and the object itself can be displayed in the format expected by the console.
> 
> It also seems to simplify the implementation on the console side.
> 
> This time it was the header that was targeted, but do other objects need to add Symbol in the same way? Or will there be a common implementation that outputs all keys/values and properties, and then override them if you want to customize them individually?

No they need to add the custom key for custom print. Otherwise it will by default display properties only
