### ISSUE TITLE
Support for `@aws-sdk/client-cognito-identity-provider`

### ISSUE THREAD

**Issue by dreamorosi** [awslabs/llrt#347]
I'd like to request adding the `@aws-sdk/client-cognito-identity-provider` to the runtime alongside the other existing optimized SDK clients.

For use cases where server-side authentication is required (i.e. custom auth flows) having this optimized client would help a lot.

I am aware that it's possible to bundle JS clients, which is what I'm doing today, however it'd be interesting to have this client as well given the existing optimized Cognito client has limited utility.

**Comment by richarddavison** [comment]
Sounds great! I'll look into it

**Comment by richarddavison** [comment]
Landed in: https://github.com/awslabs/llrt/pull/349

**Comment by dreamorosi** [comment]
Amazing! thank you for adding it so quickly.

Do you know when the next beta release will come out? Looking forward to also get this released #294

**Comment by richarddd** [comment]
Next week 🙂 This will be the last before ES2023 and minor version bump.
