### ISSUE TITLE
About the Release Cycle

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#369]
Any thoughts on the release cycle for this product?

I already know how to build from the latest commits so I am not in trouble, but some of you may be interested in downloading and using the artifacts of this product.

Also, the following websites also seem to have a mechanism to download and automatically evaluate the latest GitHub releases.

Lambda Cold Starts benchmark by maxday: 
https://maxday.github.io/lambda-perf/

Runtime compatibility:
https://runtime-compat.unjs.io/

I have the impression that the releases so far have been irregular (looking only at the duration), and I believe that regular releases are necessary (at least in the beta stage, where there are many feature additions and improvements) in order to have a correct evaluation.

For example, approximately every other week (but only if new commits occur during that period)...

Of course, this should not be a fetter on the maintainer, but we hope you will consider it. :)

**Comment by richarddavison** [comment]
Yes, we should have a bi-weekly rolling release schedule since there are so much happening. I ideally wanted to wait for ES2023 update but that is currently blocked by downstream dependencies. New release will come this week!

**Comment by nabetti1720** [comment]
Thank you for your very wise decision!

By the way, I see that you are currently describing changelog yourself. (I feel great passion!!! :)

However, there is a feature in `softprops/action-gh-release@v2` called `generate_release_notes`. 
If this is available, the work could be simplified.

**Comment by richarddavison** [comment]
> Hi @richarddavison . It's about time for the next version! :)

Yes sir :)
