### ISSUE TITLE
Error resolving module 'url'

### ISSUE THREAD

**Issue by ConjunctiveNormalForm** [awslabs/llrt#371]
Similar to #195, but in our case we don't import 'url' directly:
```
2024-05-08T15:55:04.182Z	n/a	ERROR	{
  errorType: 'ReferenceError',
  errorMessage: 'Error resolving module 'url' from '/var/task/index.mjs'',
  stackTrace: [ '' ]
}
```

We do use 'axios' though and I suspect that's what's causing the trouble?

**Comment by richarddavison** [comment]
Hi @ConjunctiveNormalForm. This has been fixed in https://github.com/awslabs/llrt/pull/304, but not yet release! We will create a new release this week.
