### ISSUE TITLE
Add rustfmt.toml to imports_granularity and group_imports option

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#386]
Hello Contributors.

Previously, in PR #328, we have implemented the addition of settings to rustfmt.toml by @yollotltam.

At that time, it seems that the following settings were not applied because of `nightly`.

- unstable_features = true
- imports_granularity = "Crate"
https://rust-lang.github.io/rustfmt/?version=v1.7.0&search=#imports_granularity
- group_imports = "StdExternalCrate"
https://rust-lang.github.io/rustfmt/?version=v1.7.0&search=#group_imports

However, lllrt has already applied `nightly build` to the toolchain and does not see the addition of these settings as a barrier. Of course, it would have to be run with `cargo +nightly fmt`.

The repeated addition of features has led to poor visibility around the `use` instruction. And I seem to have caused that too.

I would like to add the above settings to improve the efficiency and visibility of adding the `use` instruction, please let me know your thoughts.

**Comment by richarddavison** [comment]
I'm not apposed to adding this as long as we still can run on stable. It's important for us that the project still builds and runs on non-nightly toolchains.

**Comment by nabetti1720** [comment]
Thank you very much. I will think about it again when I get to `stable`.
