### ISSUE TITLE
URLSearchParams.set() not behaving like specified

### ISSUE THREAD

**Issue by chrisdirnberger** [awslabs/llrt#396]
Hey there,
I found a small little something on the URLSearchParams interface:

The URLSearchParams.set() method does not create the parameter if it does not yet exist.
Version: v0.1.14-beta

As documented here
https://url.spec.whatwg.org/#dom-urlsearchparams-set
and here
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/set
the set() method should behave like this:

> _The set() method of the URLSearchParams interface sets the value associated with a given search parameter to the given value. If there were several matching values, this method deletes the others._ 
**If the search parameter doesn't exist, this method creates it.**

In the browser both variants will return the same result, whilst running on the llrt the behavior differs.

```javascript
const searchParams = new URLSearchParams('?foo=&bar=baz');
searchParams.set('foo', 'bar');
console.log(searchParams.toString()); // returns foo=bar&bar=baz

const searchParams = new URLSearchParams('?bar=baz');
searchParams.set('foo', 'bar');
console.log(searchParams.toString()); // returns bar=baz
```

Workaround in the meantime:
```javascript
if(searchParams.has('foo')) {
  searchParams.set('foo', 'bar');
} else {
  searchParams.append('foo', 'bar');
}
```

**Comment by richarddavison** [comment]
Thanks for spotting!

**Comment by richarddavison** [comment]
Fixed in https://github.com/awslabs/llrt/pull/397
