### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by m-rph** [awslabs/llrt#42]
It's mainly the node build script that is relying on unix paths at the moment. Path.join is platform specific (which is strange since windows supports forward slashes since forever)

**Comment by AbeEstrada** [comment]
I don't think Windows is going to be supported in the near future, since QuickJS is not supported on Windows.

See: https://github.com/delskayn/rquickjs/issues/88

**Comment by richarddavison** [comment]
This will not be prioritized. You would have to rely on WSL to run LLRT on Linux for now
