### ISSUE TITLE
Is it possible to publish common modules as third-party packages, such as rquickjs-ext similar to deno?

### ISSUE THREAD

**Issue by ahaoboy** [awslabs/llrt#430]
Some common modules such as os, path, fs, etc., which are not closely coupled with the runtime, can they be extracted as separate third-party libraries? For example, rquickjs-ext, so that other projects that only use rquickjs can also use it

**Comment by richarddavison** [comment]
It probably can! We "semi-started" to support this by moving out runtime specific code to its own crate. Right now there are a couple of blockers tho:

1 There is some lambda specific features (currently gated) that reside in `llrt_core`
2 The library depends on some JS bundled code to be present (for things like ESM), this should be moved and built into `core`
3 The core module will at compile time create a perfect hashmap and embed modules into its own executable.

I experimented with a different approach for 3 by appending a special data format that contained an index of all embedded files + the raw bytecode at the end of the executable. This proved to slightly increase cold start even though it made the embedding more flexible so was ruled out.

**Comment by Sytten** [comment]
Hey I am pitching in since I started working on a utils crate for rquickjs (https://github.com/DelSkayn/rquickjs/pull/319). The goal is to eventually recreate all the api we expect for node/deno.

I would interested to help in whatever implementation like fetch.

**Comment by richarddavison** [comment]
> Hey I am pitching in since I started working on a utils crate for rquickjs ([DelSkayn/rquickjs#319](https://github.com/DelSkayn/rquickjs/pull/319)). The goal is to eventually recreate all the api we expect from node/deno for quickjs.
> 

For sure! ⭐️

> I would interested to help in whatever implementation. @richarddavison do you guys have a chat system so we can talk about that?

I just dropped you an email!

**Comment by gc-victor** [comment]
It would be great to know if there is any update about this 🙏

**Comment by ahaoboy** [comment]
Some problems I encountered during the development process, I hope the new module mechanism can improve
1. Node protocol support, that is, support for two module protocols at the same time 
```js
import fs from 'fs'

import fs from 'node:fs'
```
 
2. Module dependency, for example, fetch depends on the net module. Currently, we can only manually ensure the import order of the modules. Is it possible to implement a mechanism that reports an error or automatically imports the net module if only fetch is imported?

**Comment by richarddavison** [comment]
> Some problems I encountered during the development process, I hope the new module mechanism can improve
> 
> 1. Node protocol support, that is, support for two module protocols at the same time
> 
> ```js
> import fs from 'fs'
> 
> import fs from 'node:fs'
> ```
> 
>  2. Module dependency, for example, fetch depends on the net module. Currently, we can only manually ensure the import order of the modules. Is it possible to implement a mechanism that reports an error or automatically imports the net module if only fetch is imported?

Not quite sure I follow. Import order, does not matter.
For node protocol support we simply strip the "node:" prefix from import specifier.

**Comment by ahaoboy** [comment]
>  For node protocol support we simply strip the "node:" prefix from import specifier.

Will you consider supporting require and submodules? Many node libraries have syntax similar to the following. I don't know if there is a bundle tool that can handle it.
```js
const { isArrayBuffer } = require('node:util/types')
```

**Comment by richarddavison** [comment]
> > For node protocol support we simply strip the "node:" prefix from import specifier.
> 
> Will you consider supporting require and submodules? Many node libraries have syntax similar to the following. I don't know if there is a bundle tool that can handle it.
> 
> ```js
> const { isArrayBuffer } = require('node:util/types')
> ```

This would work if there was a a `util/types.mjs` present on the filesystem. For embedded and native modules we have to explicitly define the paths.

Require is already supported. You can also mix and match with imports in the same file

**Comment by richarddavison** [comment]
> It would be great to know if there is any update about this 🙏

Not yet, but PR is welcome. @KaanMol maybe you want to take a stab at this? The "only thing" missing right now is that we need to embed some JS modules that is required, for instance:
https://github.com/awslabs/llrt/blob/main/llrt_core/src/modules/js/%40llrt/std.ts
and https://github.com/awslabs/llrt/blob/main/llrt_core/src/modules/js/%40llrt/init.ts

There is also some AWS specific stuff in there that should not be part of the core package. I've experimented with a different approach to embed modules into the executable by [appending the bytecode to the end](appended-bytecode). It works and make building a bit simpler. However, it comes with a tiny performance cost so we might need to stick with this until I've found a better way or removed that overhead.

**Comment by KaanMol** [comment]
> > It would be great to know if there is any update about this 🙏
> 
> Not yet, but PR is welcome. @KaanMol maybe you want to take a stab at this? The "only thing" missing right now is that we need to embed some JS modules that is required, for instance: https://github.com/awslabs/llrt/blob/main/llrt_core/src/modules/js/%40llrt/std.ts and https://github.com/awslabs/llrt/blob/main/llrt_core/src/modules/js/%40llrt/init.ts
> 
> There is also some AWS specific stuff in there that should not be part of the core package. I've experimented with a different approach to embed modules into the executable by [appending the bytecode to the end](appended-bytecode). It works and make building a bit simpler. However, it comes with a tiny performance cost so we might need to stick with this until I've found a better way or removed that overhead.

I wonder if making the core modules AWS stuff free is not a blocking piece before continuing. I could take a look next week :)

**Comment by KaanMol** [comment]
@richarddavison would it be possible I could also get an invite for the chat system?

**Comment by Sytten** [comment]
I will post it here since I am in charge of it.
Here is the discord: https://discord.com/invite/pyMppMngYU

**Comment by Sytten** [comment]
One thing I wanted to mention is that modules should be more independent than they are right now. For example the URL module cant be evaluated at the moment if the http module init is not called first because some stuff like URL constructor is put in the globals in the http init and taken back in the module eval.

**Comment by KaanMol** [comment]
> One thing I wanted to mention is that modules should be more independent than they are right now. For example the URL module cant be evaluated at the moment if the http module init is not called first because some stuff like URL constructor is put in the globals in the http init and taken back in the module eval.

They share a lot of code and components, so making everything completely standalone from the start might not be the best approach. Instead, it would be better to develop something that improves over time. It may not be ideal to have everything as separate crates like Deno does. This raises the question of how standalone "standalone" should be.

Most modules consist largely of shared code or are very small. It would make more sense to have a crate like "llrt_modules" with feature flags, to be honest.

**Comment by Sytten** [comment]
Yeah probably but for a user I should not have to know the internals of the modules to know that the http module must be included for the URL module to work is what I am saying.

**Comment by ahaoboy** [comment]
This is a problem. The simplest way is to provide a full list of dependencies for each module. If necessary APIs are not supported during compilation or runtime, an error should be reported and the dependencies should be added one by one according to the order given in the document.

**Comment by richarddavison** [comment]
Yeah there is no straight answer here. Feature flags may be the simplest, however with the downside of being able to toggle modules or features  at runtime.
I think we need to rework the module builder to also include dependencies. This can be done by simply passing the module builder to a trait responsible for registering each module. 
Also should automatically expose methods on global scope as defined by the module. Users should then be able to opt out of global scope and only register a module

**Comment by Sytten** [comment]
Alright I started work on that. @richarddavison when you have 2s, can you join the discord :)
I agree on the refactor of the module builder, but this can be done independently.
My goal is to start by splitting of at the `ModuleInfo` level and let the user handle the module registration for now.

**Comment by stephencroberts** [comment]
It's great to see the direction this is headed! We use rquickjs for our JavaScript runtime that runs in WASM and are starting to hand-select modules from LLRT to include in our runtime (so we don't have to write them all from scratch!), so a library of modules is exactly what we're looking for. Targeting `wasm32-wasi` is a challenge, so we have our own fork of LLRT right now to compile just what we need with some modifications, but I imagine others would like to target `wasm32-wasi` as well.

I remember seeing some discussion somewhere about where the crate should go -- would love to see the library more rquickjs focused than LLRT which would probably make it easier to target WASM anyways. I'll join the discord and tag along in case I can help.

**Comment by nabetti1720** [comment]
Hi @Sytten , I think this is a wonderful initiative. :)
It seems that `os.rs` and `url.rs`, which currently reside directly under the modules directory, could also be easily separated.

**Comment by Sytten** [comment]
@nabetti1720 Yup totally. The fs was the original module to test and I will port others.

I do think I want to work on a better Module trait first like we discussed in multiple places to unify the init functions, ModuleDef, ModuleInfo and dependencies between modules.

That would make scaling the modules easier for people.

**Comment by nabetti1720** [comment]
> @nabetti1720 Yup totally. The fs was the original module to test and I will port others.
> 
> I do think I want to work on a better Module trait first like we discussed in multiple places to unify the init functions, ModuleDef, ModuleInfo and dependencies between modules.
> 
> That would make scaling the modules easier for people.

The port from `llrt_core` to `llrt_module` will be a good theme for new contributors to LLRT.
Since we are in the mood, we note here that the following modules are also eligible. :) ( Ref #468 )

- llrt:hex
- llrt:xml
