### ISSUE TITLE
Make URL and URLSearchParams more compliant with WHATWG URL specification

### ISSUE THREAD

**Issue by stephencroberts** [awslabs/llrt#437]
In trying to use the `URL` module, I quickly found that it's not compliant with the [URL standard](https://url.spec.whatwg.org/) for many normal use-cases. The first issue I came across was with the handling of the `#` for hashes (fragments) in both getting and setting the hash, so I decided to set up the [web-platform-tests for url](https://github.com/web-platform-tests/wpt/tree/b634532883c8dd54ac7ef4a29b5eccaf5125359f/url) as part of the LLRT unit test suite which uncovered a host of other issues for common web use-cases. I have a fork of LLRT that I'm using, and I've updated `URL` and `URLSearchParams` to pass a vast majority of the tests (the rest need to be fixed in the `Url` crate). Are you open to a Pull Request?

**Comment by Sytten** [comment]
I also created another variant of URLSearchParams here for reference https://github.com/DelSkayn/rquickjs/blob/bf699539bab3caacc23cadb3abbde9f1ae95160f/util/src/url_search_params.rs
