### ISSUE TITLE
uuid implementation needs to be updated

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#472]
For the uuid functionality provided by [external package](https://www.npmjs.com/package/uuid?activeTab=readme) in node.js, LLRT natively implements it, which contributes to speeding up the process.

However, new methods and properties have been created in current node.js packages, making them incompatible.
A quick check shows that the following methods and properties supported since uuid@9.1 are not supported in LLRT.

- uuid.MAX
- uuid.v1ToV6()
- uuid.V6()
- uuid.v6ToV1()
- uuid.V7()

In the ESBUILD example in the README, uuid is excluded with the `--external` option, so I believe we need to aim for full compatibility.
Fortunately, the [uuid crate](https://docs.rs/uuid/1.10.0/uuid/) used by LLRT seems to be compatible with v6 and v7 generation, and the other methods and properties can be hinted at by the node.js package implementation.

**Comment by richarddavison** [comment]
I think we can ignore these and add a `llrt:uuid` prefix
