### ISSUE TITLE
UTF-16BE encoding support

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#484]
LLRT implements `UTF-16LE` encoding using only the functions provided by rust as standard.

Currently, it is `ICU disable` in Node.js.
https://nodejs.org/api/util.html#encodings-supported-when-icu-is-disabled

With reference to the `UTF-16LE` implementation, it is not too difficult to add support for `UTF-16BE` to achieve `small-icu` status.
https://nodejs.org/api/util.html#encodings-supported-when-nodejs-is-built-with-the-small-icu-option

This would be just the task for someone who wants to contribute to this project. 👍

**Comment by richarddavison** [comment]
Agree! This should be pretty simple to implement

**Comment by nabetti1720** [comment]
The issue has been resolved and will be closed.
