### ISSUE TITLE
further advances in uuid compatibility

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#485]
We have renamed the native implementation to `llrt:uuid` to avoid conflicts with existing Node.js package names. (See also #472) 
Next, to make this native `llrt:uuid` even better (for greater compatibility with uuid packages), we believe the following features can be implemented relatively easily.

- uuid.MAX
- uuid.v1ToV6()
- uuid.V6()
- uuid.v6ToV1()
- uuid.V7()

Fortunately, the [uuid crate](https://docs.rs/uuid/1.10.0/uuid/) used by LLRT seems to be compatible with v6 and v7 generation, and the other methods and properties can be hinted at by the [node.js package implementation](https://github.com/uuidjs/uuid/tree/main/src).

We are hopeful that this feature will be picked up by someone who needs it and wants to contribute in some way to this project. :)

**Comment by kevinmingtarja** [comment]
Hi, I'm interested in contributing to this!

**Comment by Sytten** [comment]
Would be nice to move to module to llrt_modules too.
