### ISSUE TITLE
SyntaxError: Could not find export 'webcrypto' in module 'crypto'

### ISSUE THREAD

**Issue by aleksasiriski** [awslabs/llrt#537]
Is this related to https://github.com/awslabs/llrt/issues/184? If so, this can be closed. Otherwise, I'm a little confused :)

I get this when running locally on Fedora Kinoite x86_64 with llrt-linux-x86 binary. I also tried the lambda-arm64 binary within arm64 lambda but there I get the following:

```
2024-08-11T19:10:15.339Z	n/a	FATAL	TypeError: String contained internal null bytes: nul byte found in provided data at position: 7
  
INIT_REPORT Init Duration: 24.23 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
2024-08-11T19:10:52.147Z	n/a	FATAL	TypeError: String contained internal null bytes: nul byte found in provided data at position: 7
  
INIT_REPORT Init Duration: 25.43 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
START RequestId: XXX Version: $LATEST
RequestId: XXX Error: Runtime exited with error: exit status 1
Runtime.ExitError
END RequestId: XXX
REPORT RequestId: XXX	Duration: 26.40 ms	Billed Duration: 27 ms	Memory Size: 3008 MB	Max Memory Used: 23 MB	
```

To note, I'm trying to run SvelteKit using LLRT for improved cold starts, I bundled the JS as per instruction: ES2023

**Comment by richarddavison** [comment]
Hi, yes it's related to https://github.com/awslabs/llrt/issues/537.

ES2023 is in upcoming 0.2-beta. Will release next week :)
