### ISSUE TITLE
llrt always maintains a certain cpu usage when running, what is the reason

### ISSUE THREAD

**Issue by 2234839** [awslabs/llrt#546]
node.js has a 0% cpu footprint when running a js file that contains only one setInterval, while llrt consistently maintains a 25% cpu footprint (on a 2-core, 4-thread machine).
Is this due to the different implementation of the event mechanism?and will it be possible to improve this aspect in the future

**Comment by richarddavison** [comment]
This seems like a bug. Can you share a reproducable?

**Comment by 2234839** [comment]
@richarddavison 
![图片](https://github.com/user-attachments/assets/21fad96c-9b7b-4adb-9e09-8915cfbeb6c9)
```test.js
setInterval(() => {
  console.log(Date.now());
}, 5000);
```
llrt-linux:https://github.com/awslabs/llrt/releases/download/v0.2.0-beta/llrt-linux-x64.zip

system info：Linux pop-os 6.9.3-76060903-generic #202405300957~1721174657~22.04~abb7c06 SMP PREEMPT_DYNAMIC Wed J x86_64 x86_64 x86_64 GNU/Linux
AMD FX-9800P RADEON R7, 12 COMPUTE CORES 4C

**Comment by 2234839** [comment]
I'm running on my other linux, which also uses a cpu
![图片](https://github.com/user-attachments/assets/278065dd-c8a4-4d90-9531-1ef7d8e70f77)

**Comment by 2234839** [comment]
I just tested version 0.1.15 and it worked fine with me, running the js above with 0 cpu usage

**Comment by richarddavison** [comment]
Confirming It’s the new timer implementation that pollutes the task queue. I will revert to the old implementation and roll out a fix ASAP. Thanks for reporting ⭐️

**Comment by 2234839** [comment]
@richarddavison  I think the new timer implementation still solves some problems, because I ran into the following strange problem with 0.1.15, which the latest version does not have
```js
const net = require("net");
const server2 = net.createServer((socket) => {
  // The call here is only start net, not end net
  handle("net");
});
server2.listen(8087);

async function handle(tag) {
  console.log("start", tag);
  const r = await 1;
  console.log("end", tag);
}

setTimeout(() => {
  // The call here gets the correct result
  // start time
  // end time
  handle("time");
}, 1000);

```

**Comment by richarddavison** [comment]
> @richarddavison I think the new timer implementation still solves some problems, because I ran into the following strange problem with 0.1.15, which the latest version does not have
> 
> ```js
> const net = require("net");
> const server2 = net.createServer((socket) => {
>   // The call here is only start net, not end net
>   handle("net");
> });
> server2.listen(8087);
> 
> async function handle(tag) {
>   console.log("start", tag);
>   const r = await 1;
>   console.log("end", tag);
> }
> 
> setTimeout(() => {
>   // The call here gets the correct result
>   // start time
>   // end time
>   handle("time");
> }, 1000);
> ```

I tested this scenario with the code in the fix PR and it behaves as expected 🙌
