### ISSUE TITLE
fetch support octet-stream;base64

### ISSUE THREAD

**Issue by ahaoboy** [awslabs/llrt#565]
This is not a valid http url, but in some scenarios it is convenient to use this form to embed binary files in the program.

```js
const s = "hello"
const base64 = Buffer.from(s).toString("base64");
const dataURIPrefix = "data:application/octet-stream;base64,";
const url = dataURIPrefix + base64;
const resp = await fetch(url);
const buf = await resp.arrayBuffer();
const str = Buffer.from(buf).toString("ascii");
console.log(str === s);
```

**Comment by nabetti1720** [comment]
This would cause an error if parsed into a normal URI class (and indeed it did).

https://fetch.spec.whatwg.org/#data-urls

It seems to me that the fetch implementation needs a unique shortcut process (i.e., process the data url and return the response as-is, without external communication).

Would you like me to do some research?

**Comment by ahaoboy** [comment]
> Would you like me to do some research?

Feel free to do it
