### ISSUE TITLE
support node:module and createRequire

### ISSUE THREAD

**Issue by ahaoboy** [awslabs/llrt#581]
https://nodejs.org/api/module.html#modulecreaterequirefilename

Many third-party libraries use this API to read version information, but require cannot be optimized by the bundler
```js
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);

const { version }= require("./package.json")

console.log(version)
```

This simple implementation should cover most scenarios, but it is better to refer to the implementation of node and deno
```js
export function createRequire(){
  return globalThis.require
}  
```

require is a very common global function, and could probably be added to llrt_module as well.

**Comment by richarddavison** [comment]
This is already implemented: https://github.com/awslabs/llrt/blob/a161f394391b396aaa6980053de1da1acccf886a/llrt_core/src/modules/module.rs#L20

**Comment by ahaoboy** [comment]
It seems to be a problem caused by path processing on Windows

```rust
pub fn join_path(parts: Vec<String>) -> String {
    let mut result = PathBuf::new();
    let mut empty = true;
    for part in parts.iter() {
        if part.starts_with(MAIN_SEPARATOR) && empty {
```
