### ISSUE TITLE
No full AWS SDK binary for macOS in the releases

### ISSUE THREAD

**Issue by ainsleyrutterford** [awslabs/llrt#590]
I'm trying to import `@aws-sdk/client-cloudwatch` in my code. According to the README, it looks like I should use the `-full-sdk` binary when doing so. However, looking at the releases I can only see the following binaries for macOS:

- `llrt-darwin-arm64.zip`
- `llrt-darwin-x64.zip`

Should the `-full-sdk` binary for macOS be added to the releases so that people don't have to build from source to generate the binary?

Thanks! (loving LLRT btw!)

**Comment by richarddavison** [comment]
Yes, we should add this to releases as well! Thanks for your suggestion!

**Comment by nabetti1720** [comment]
Until now, I had to forego multi-flavor support other than `llrt-lambda-*` and `llrt-container-*` because I was not sure how much need there would be.

Now that I am aware of the need, I will work on it. :)
