### ISSUE TITLE
How do we use a non-included AWS SDK?

### ISSUE THREAD

**Issue by ainsleyrutterford** [awslabs/llrt#591]
According to the README:

> For an example on how to use a non-included SDK, see [this example build script (buildExternalSdkFunction)](https://github.com/awslabs/llrt/blob/main/example/functions/build.mjs)

I don't understand what's being done in the example that enables the use of a non-included SDK. The only difference I can see from the standard ESBuild command provided in the README:

> ```
> esbuild index.js --platform=node --target=es2023 --format=esm --bundle --minify --external:@aws-sdk --external:@smithy
> ```

is that there are more values provided in [the `external` argument](https://github.com/awslabs/llrt/blob/main/example/functions/build.mjs#L63C1-L69C7):

```
external: [
  "@smithy",
  "@aws-sdk/core",
  "@aws-sdk/util-user-agent-browser",
  "@aws-crypto",
  "bowser",
],
```

I must be missing something! Why would the non-included SDK (`@aws-sdk/client-ec2` in the example provided) now be part of the ESBuild bundle?

Thanks!

**Comment by ainsleyrutterford** [comment]
Ohhh, is it because `@aws-sdk/core` is in `external` rather than `@aws-sdk`? I didn't spot that difference! If that is the reason, maybe the README should state that explicitly or a comment could be added to the example?

**Comment by richarddavison** [comment]
> Ohhh, is it because `@aws-sdk/core` is in `external` rather than `@aws-sdk`? I didn't spot that difference! If that is the reason, maybe the README should state that explicitly or a comment could be added to the example?

Yes that's exactly it! Thanks for your suggestion, this should probably documented better!
