### ISSUE TITLE
TypeError: cannot set property 'prop' of undefined

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#607]
We are currently working on a node_module loading implementation, but the following syntax used in some npm packages causes an error in LLRT.

```javascript
module.exports.prop = 'a';
console.log(module.exports.prop);
```

In LLRT: 
```
% llrt ./src/reproduction.js 
TypeError: cannot set property 'prop' of undefined
  at <anonymous> (src/reproduction.js:1:23)
```

In Node.js:
```
% node ./src/reproduction.js
a
```

**Comment by richarddavison** [comment]
I think the issue here is that LLRT assumes the loaded file is an ES module. What if you create another file and do a a `require(./src/reproduction.js)`? The fix here would be to basically have a require wrapper for the index file loaded via cmd line argument.

**Comment by nabetti1720** [comment]
I loaded it via require and the situation did not change.

```javascript
const a = require("reproduction.js")
```

```
% llrt ./src/main.js 
{}
TypeError: not a function
  at <anonymous> (/Users/shinya/Workspaces/hono-test/src/reproduction.js:4:17)
      at <anonymous> (src/main.js:1:11)
```

By the way, I created the reproduced code for this issue, but originally found it in the node_modules that were loaded in the require test.

For example, the following module:

```javascript
// ./src/reproduction.js 
var iconv = require('iconv-lite');
```

```
llrt ./src/reproduction2.js 
TypeError: cannot set property 'encodings' of undefined
  at <anonymous> (/Users/shinya/Workspaces/hono-test/node_modules/iconv-lite/lib/index.js:12:19)
      at <anonymous> (src/reproduction2.js:1:13)
```

**Comment by richarddavison** [comment]
I have located the issue. It's in the CJS implementation. Will create a PR and ASAP

**Comment by richarddavison** [comment]
This should now work as expected in the latest PR https://github.com/awslabs/llrt/pull/609/files. Also added a test case for this
