### ISSUE TITLE
Support for crypto createCipher/createDecipher functions?

### ISSUE THREAD

**Issue by ThomasAribart** [awslabs/llrt#612]
Hello and thanks for this wonderful tool 🙌

The docs stipulate that the native `crypto` module is fully supported, however, when trying to use `createCipher` or `createCipheriv` functions, I get the following errors:

```
Could not find export 'createCipher' in module 'crypto'
```

Is there anything special I need to do to enable those functions?

**Comment by richarddavison** [comment]
Hi @ThomasAribart, thanks for your comment. This is currently in progress and it's currently not available. Thanks for your patience :) See https://github.com/awslabs/llrt/issues/184

**Comment by ThomasAribart** [comment]
Alright thanks!
