### ISSUE TITLE
`llrt compile` output binary runtime error

### ISSUE THREAD

**Issue by moderation** [awslabs/llrt#622]
The binary that results from `llrt compile <file.js>` no long runs and returns the error on the last line below.

```
llrt compile hello_console.js
llrt hello_console.lrt
ReferenceError: Error resolving module 'hello_console.lrt'
```

**Comment by nabetti1720** [comment]
Sorry, when we did a major refactor of the node_modules loading, we did not test enough for the current directory (no path specified). I have reproduced the event on my laptop as well and will work on a fix. Please give me some time.

**Comment by moderation** [comment]
Awesome. Thanks. I have a modified `Makefile` that lets me build `llrt` on MacOS Apple Silicon that works and it is getting a different but related module error trying to run any file

**Comment by richarddavison** [comment]
@nabetti1720 we should add some test cases for this as well :)

**Comment by moderation** [comment]
Compilation on Linux `arm64` and `amd64` broken at the moment with `snmalloc-sys` compile errors, but I've confirmed that the latest PR fixes `llrt compile` on MacOS.

There is another issue on MacOS in that you must supply the full path name for the script you are running. Also aware that MacOS isn't a target platform

This works
```
llrt $PWD/hello_console.js
Hello world!
```
This doesn't
```
llrt hello_console.js
ReferenceError: Error resolving module 'hello_console.js' from '/Users/moderation/Applications/runtime/eval_script'
```
