### ISSUE TITLE
New version 

### ISSUE THREAD

**Issue by paul-uz** [awslabs/llrt#633]
Looks like there has been a lot of work in the past month since the last version was released.

Could we get a new version if possible?

Would be good to get weekly releases or some kind of timeline/roadmap

**Comment by richarddavison** [comment]
New release next week! We'll also increase the release cadence to bi-weekly!

**Comment by richarddavison** [comment]
@paul-uz see https://github.com/awslabs/llrt/issues/635

**Comment by paul-uz** [comment]
Wasn't meaning to pester, just wanted to get an update as I'm eager to use this runtime!

**Comment by richarddavison** [comment]
> Wasn't meaning to pester, just wanted to get an update as I'm eager to use this runtime!

No worries, this has been asked before so happy to give some more information!

**Comment by richarddavison** [comment]
https://github.com/awslabs/llrt/releases/tag/v0.3.0-beta
