### ISSUE TITLE
Can't import CJS modules via ESM import statement

### ISSUE THREAD

**Issue by nabetti1720** [awslabs/llrt#641]
While verifying the loading of the Node.js package, we encountered another strange event.

```javascript
// logger.js
import { Logger } from '@aws-lambda-powertools/logger'
const logger = new Logger()
logger.info('Hello world')
```
```
% llrt logger.js 
SyntaxError: Could not find export 'default' in module '/Users/shinya/Workspaces/llrt-test/node_modules/lodash.merge/./index.js'
  at <anonymous> (eval_script:1:5)

% node logger.js 
{"level":"INFO","message":"Hello world","sampling_rate":0,"service":"service_undefined","timestamp":"2024-10-22T13:47:00.450Z"}

% bun logger.js 
{"level":"INFO","message":"Hello world","sampling_rate":0,"service":"service_undefined","timestamp":"2024-10-22T13:50:09.638Z"}
```

While investigating reproduction methods, we found that the same event reproduced itself in the following application structure.

```javascript
// hello.js
var hello = function world() {
  return "hello world"
}
module.exports = hello;
```
```javascript
// main.js
import hello from './hello.js'
console.log(hello())
```

```
% llrt main.js
SyntaxError: Could not find export 'default' in module '/Users/shinya/Workspaces/llrt-test/./hello.js'
  at <anonymous> (eval_script:1:5)

% node main.js  
file:///Users/shinya/Workspaces/llrt-test/main.js:1
import hello from './hello.js'
       ^^^^^
SyntaxError: The requested module './hello.js' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:171:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:254:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

Node.js v22.9.0

% bun main.js 
hello world
```

The same event occurs with Node.js in this way. However, the behavior changes when `hello.js` is changed to `hello.cjs`.

```javascript
// main.js
import hello from './hello.cjs' // The content is exactly the same as hello.js
console.log(hello())
```

```
% llrt main.js 
SyntaxError: Could not find export 'default' in module '/Users/shinya/Workspaces/llrt-test/./hello.cjs'
  at <anonymous> (eval_script:1:5)

% node main.js 
hello world

% bun main.js 
hello world
```

The following is what we can assume from these findings:
- Bun has the ability to import CJS files.
- Node.js has the ability to import CJS files with the help of package definitions or extensions.
- LLRT does not support either.

**Comment by richarddavison** [comment]
Hi @nabetti1720 thanks for reporting. This is also quite complex as all import statement currently goes though the "resolver/loader" procedure. I've tested an approach where we detect inside the loader if we should resolve a CJS module and then generate a source file which internally uses our require function to then re-export that. This proved to be more difficult due to cyclic issues as we won't run the loader again which is inside the require code. I need to think about a different approach to this problem.

**Comment by nabetti1720** [comment]
When we encounter a module like this one, instead of loading the module as is, can we wrap it in the following code and load it?

```rust
[“{default: ", code, "}”].concat()
```

It was inspired by the following code, which we discovered during our research on another issue.

```
function _interopRequireDefault(e) { return e && e.__esModule ? e : { default: e }; }
```

**Comment by richarddavison** [comment]
I've got a fix for this. We can't simply do string concatenation as this is much more complex. Will submit PR soon and you can see the fix :)

**Comment by nabetti1720** [comment]
@richarddavison . Unfortunately, I have tried with the latest commit(#d2a5f66) and this problem does not seem to have been resolved...

```javascript
// hello.js
var hello = function world() {
  return "hello world"
}
module.exports = hello;
```

```javascript
// main.js
import hello from './hello.js'
console.log(hello())
```

```
% llrt main.js
SyntaxError: Could not find export 'default' in module '/Users/shinya/Workspaces/llrt-test/hello.js'
  at <anonymous> (eval_script:1:5)
```

However, if the file extension to require is set to cjs, there is an improvement.

```javascript
// main.js
import hello from './hello.cjs' // The content is exactly the same as hello.js
console.log(hello())
```

```
% llrt main.js
hello world
```

**Comment by nabetti1720** [comment]
My understanding is that the current implementation is correct because I believe that the extension inherently contains information to determine if it is a CJS or an ESM.

But since these use cases work in other runtimes, I believe that other runtimes implement more complex logic than the determination by extension.

I think LLRT should first have an option (e.g., an environment variable) to temporarily cancel the strict decision to accommodate these use cases, while keeping the existing implementation as much as possible. Then I can enable that option and continue the validation.

After that, we believe a better approach would be to implement an automatic decision-making process.

**Comment by richarddavison** [comment]
We can also force all require() statements to treat imports as CJS (that can also export things)

So this would work:
```
module.export.a= 1;
export const b = 2;
```

**Comment by nabetti1720** [comment]
> We can also force all require() statements to treat imports as CJS (that can also export things)

What does this mean? Does it mean replacing the `Module::declare()` at the end of the loader with a call to `self::load_cjs_module()`?

https://github.com/awslabs/llrt/blob/d18dcf3f897f793aa026c18b90c9277cf4e3bc8f/llrt_core/src/module_loader/loader.rs#L178
