### ISSUE TITLE
move require to llrt_modules 

### ISSUE THREAD

**Issue by ahaoboy** [awslabs/llrt#645]
llrt require is implemented in the llrt_core module

If it can be implemented in llrt_modules, it will make it easier for other rquickjs projects to use cjs modules.
```
use llrt_modules::{ require::{init}};

init(ctx)
```

```
require('fs')
```

**Comment by nabetti1720** [comment]
It's a bit chaotic in `vm::init()` and could be a bit more organized.

- related `number` -> llrt_number (new)
- related `json` -> llrt_json (additional)
- related `require` -> llrt_require (new)

**Comment by ahaoboy** [comment]
simd_json is also a great feature. If it can be moved into llrt_modules, more projects can benefit from it.

**Comment by Sytten** [comment]
Dont know if you saw @ahaoboy but I refactored the modules into individual ones, simd_json is already in `llrt_json`

**Comment by richarddavison** [comment]
Agree that require can be moved out. We need to figure out a better convention & traits for providing modules first tho that supports with and without global and module definition. Something like:



```rust
struct HttpModule{}
impl GlobalModule for FsPromisesModule{
...
}

impl ModuleDef for FsPromisesModule{
...
}
```

**Comment by Sytten** [comment]
Yeah but there is still the problem of settings, I thought the user data that was added recently would solve it but it doesn't really

**Comment by nabetti1720** [comment]
We would be very happy if you could simplify the usage of the module according to the situation of the trait you are implementing. For example, the following mean the same thing.

```rust
impl Default for ModuleBuilder {
    fn default() -> Self {
        Self::new()
            .with_module(CryptoModule)
            .with_global(crate::modules::crypto::init)
    }
}
```

```rust
impl Default for ModuleBuilder {
    fn default() -> Self {
        Self::new()
            .attach(CryptoModule) // Call only those implementations that exist as modules or global.
    }
}
```

Also, this is a little off topic, but I think the fact that some modules require a call to `with_global()` before `with_module()` needs to be improved.

**Comment by richarddavison** [comment]
Also require is very complicated as it needs to drive the “event loop” forward. Right now we’re patching rquickjs in core to make promises poll futures in the scheduler. It this isn’t patched, timers inside require statements will never execute as the futures are never polled.
