### ISSUE TITLE
ReferenceError: Error resolving module 'C:codellrt/index' from 'eval_script'

### ISSUE THREAD

**Issue by ahaoboy** [awslabs/llrt#679]
Downloading precompiled executable programs or compiling and executing them locally will result in an error.

https://github.com/awslabs/llrt/actions/runs/11851308126

```
cargo run 
```

win
```
ReferenceError: Error resolving module 'C:codellrt/index' from 'eval_script'
```

linux
```
ReferenceError: Error resolving module '/root/llrt/index' from 'eval_script'
```

**Comment by ahaoboy** [comment]
Tjs's repl is implemented in js, but it needs to be able to read user input on the js side

https://github.com/saghul/txiki.js/blob/master/src/js/run-repl/index.js

**Comment by richarddavison** [comment]
> Wiindows needs to process path separators
> 
> ```
> std::env::current_dir()
> 
> C:\code\llrt\llrt
> ```
> 
> The file path passed in on windows also needs to be processed
> 
> ```
>  cr -- 'C:\\code\\llrt\\bundle\\js\\@llrt\\test\\index.js'
> ```
> 
>  ```
> 
>                 if is_supported_ext(ext) {
>                     if file_exists {
>                         eprintln!("{}", arg);
>                         return vm.run_file(arg.replace("\\", "/"), true, global).await;
>                     } else {
>                         eprintln!("No such file: {}", arg);
>                         exit(1);
>                     }
>                 } else {
> ```

Path separators should be handled by the loader. Please run with` LLRT_LOG=trace cargo run` and report back

**Comment by richarddavison** [comment]
You're right, this gets replaced in input! Fixing right away!

**Comment by ahaoboy** [comment]
> Path separators should be handled by the loader. Please run with` LLRT_LOG=trace cargo run` and report back


```
2024-11-16T02:48:20.034Z TRACE llrt: Started runtime 
2024-11-16T02:48:20.036Z TRACE llrt: Initialized VM in 2ms 
2024-11-16T02:48:20.036Z TRACE llrt_core::module_loader::resolver: Try resolve 'C:/code/llrt/llrt/index' from 'eval_script' 
2024-11-16T02:48:20.036Z TRACE llrt_core::module_loader::resolver: require_resolve(x, y):(C:/code/llrt/llrt/index, eval_script) 
2024-11-16T02:48:20.036Z TRACE llrt_core::module_loader::resolver: |  load_as_file(x): C:/code/llrt/llrt/index 
2024-11-16T02:48:20.036Z TRACE llrt_core::module_loader::resolver: |  load_as_directory(x): C:/code/llrt/llrt/index 
2024-11-16T02:48:20.037Z TRACE llrt_core::module_loader::resolver: |  load_index(x): C:/code/llrt/llrt/index
ReferenceError: Error resolving module 'C:/code/llrt/llrt/index' from 'eval_script'

```

**Comment by nabetti1720** [comment]
> ```
> ReferenceError: Error resolving module 'C:/code/llrt/llrt/index' from 'eval_script'
> ```

In this log, the Windows path expression appears to be correct. The reason why you are currently getting a resolve error is because the index.(js | mjs | cjs | lrt) file does not exist in the execution directory.

When no arguments are specified at runtime in LLRT, it searches for the corresponding file in the execution directory.

**Comment by ahaoboy** [comment]
> When no arguments are specified at runtime in LLRT, it searches for the corresponding file in the execution directory.

I see. I thought running llrt directly would enter a repl similar to nodejs.

**Comment by richarddavison** [comment]
Fixed in https://github.com/awslabs/llrt/pull/681
