### ISSUE TITLE
support custom loader

### ISSUE THREAD

**Issue by ahaoboy** [awslabs/llrt#692]
How can llrt pass in a custom loader to process ts/tsx

```
        let loader = (module_loader, CustomLoader);
        runtime.set_loader(resolver, loader).await;
```

I want to add the ability to run ts/tsx,  but this will greatly increase the package size(28mb), so it would be useful to be able to add a custom loader through configuration

https://github.com/awslabs/llrt/commit/2004c001d7d8f161388a49187b1caaccd30896c0

**Comment by richarddavison** [comment]
It's not really recommended. Typescript should ideally be processed at compile time.
https://github.com/awslabs/llrt?tab=readme-ov-file#running-typescript-with-llrt

**Comment by ahaoboy** [comment]
> It's not really recommended. Typescript should ideally be processed at compile time

This is not to add ts support to llrt, but to hope that llrt_core can add the ability to customize the loader, allowing developers to develop other programs based on llrt_core and add the desired functions to it, such as ts and wasm support.
