### ISSUE TITLE
Node-Bindings lib doesn't seem to work

### ISSUE THREAD

**Issue by codingnuclei** [awslabs/llrt#704]
Hi 👋

I have been experimenting with trying to get Kafka working with llrt.

There are few libs out there to do this in nodejs, but many have limited activity.  With this in mind I have opted for [confluent's](https://github.com/confluentinc/confluent-kafka-javascript) offering.

It is a JavaScript binding for a native C implementation of kafka. The lib uses [node-bindings](https://www.npmjs.com/package/bindings) underhood.

It seems to work well in node, but when I switch to llrt it falls over erorring within the binding lib.

Is this something we would expect to work? 

Happy to create a repo showing the issue if that is the case.

Thanks 🙏

**Comment by richarddavison** [comment]
Hi @codingnuclei thanks for your comment. Unfortunately this won't work. Native node extensions are heavily dependent on V8 primitives. These can technically be emulated but would be a massive undertaking. The rationale right now is to keep this simpler and if you need native node modules you unfortunately have to stick with Node.

**Comment by codingnuclei** [comment]
Ok makes sense. Thanks
