### ISSUE TITLE
Doest this project interested in supporting wasm32-wasip1 target?

### ISSUE THREAD

**Issue by oliverzy** [awslabs/llrt#723]
I'm porting llrt to wasm32-wasip1 target, I have made some progress.
My use case is running llrt in the browser.

**Comment by nabetti1720** [comment]
I'd like to ask you because I'm personally interested, what are the benefits of running LLRT in a browser? What kind of Javascript application are you trying to run with LLRT in the browser?

**Comment by oliverzy** [comment]
We are developing a browser based cloud development environment which is a little bit similar to stackblitz web container. Unlike web container, it can run any program that target wasm32-wasip1.
We basically implement a wasip1 host in browser. Right now we are porting llrt to wasi because we need a nodejs compatible runtime.

The current status is we can run most of the module's successfully with some patches other than network module.

We will start to work on the network module this week.

**Comment by ahaoboy** [comment]
https://github.com/justjake/quickjs-emscripten is a qjs wasm project that can run in the browser
