### ISSUE TITLE
Using JSON.parse on an object does not throw an error

### ISSUE THREAD

**Issue by georeeve** [awslabs/llrt#724]
When trying to use `JSON.parse` on an object instead of a string, LLRT silently fails without throwing an error.

**Example lambda**
```typescript
const main = async (event: { detail: { payload: string } }) => {
    console.log(typeof event.detail.payload);
    console.log(JSON.parse(event.detail.payload));
};
```

**Logs on LLRT**
```json
{
    "level": "INFO",
    "message": "object"
}
```

**Logs on Node.js**
```json
{
    "level": "INFO",
    "message": "object"
}
{
    "level": "ERROR",
    "message": {
        "errorType": "SyntaxError",
        "errorMessage": "\"[object Object]\" is not valid JSON",
        "stackTrace": [
            "SyntaxError: \"[object Object]\" is not valid JSON",
            "    at JSON.parse (<anonymous>)",
            "    at Runtime.g [as handler] (/var/task/index.js:1:543)",
            "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"
        ]
    }
}
```

**Comment by richarddavison** [comment]
Hi @georeeve. Thanks for the report. Are you able to provide the payload here? This skould not happen.

**Comment by georeeve** [comment]
@richarddavison I'll try and dig through and find it again for you. I'm guessing that as it didn't even run the console.log, the code panicked here? If so, is there a way to view panic logs within Lambda?

**Comment by georeeve** [comment]
I've just tried to run a basic payload of `JSON.parse({ test: 'test' })` and I'm still not getting any logs from that, but Node.js still errors as above.

**Comment by richarddavison** [comment]
I think we can test with:` \"[object Object]\"` or passing any object for that matter.

**Comment by richarddavison** [comment]
Can you try disable JSON log format and see if that's the issue?

**Comment by richarddavison** [comment]
I've found the issue here, it's log level filter logic that has been inverted. I'll submit patch today!

**Comment by georeeve** [comment]
Great, thanks for looking into it.
