### ISSUE TITLE
[Request] Add @aws-sdk/client-verifiedpermissions to the list of supported SDK

### ISSUE THREAD

**Issue by Jimmy89** [awslabs/llrt#727]
Hello all,

I'm considering the usage of the llrt for our custom lambda authorization function within our AWS Appsync API. The lambda needs to handle some traffic and we want to get as fast as possible through the authorization part. Therefore, llrt seems as a good fit.

We are using AWS Verified Permission to handle the authorization. I'm wondering whether it would be possible to implement the "@aws-sdk/client-verifiedpermissions" library within the full sdk package of lrrt. I have no clue what kind of effort is required for such a request, so I'm asking the question.

**Comment by nabetti1720** [comment]
The system is already in place, so if there is a specific use case, I don't think it would be too difficult to support it.
